// cloudflow-frontend-vue/src/pages/hr/HrRecruitmentPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import {
  Briefcase,
  CalendarClock,
  CheckCircle2,
  ClipboardCheck,
  Plus,
  RefreshCcw,
  Save,
  UserRoundSearch,
  XCircle
} from 'lucide-vue-next'
import {
  BaseDialog,
  Button,
  DataTable,
  Input,
  Panel,
  Select,
  StatusBadge,
  TextArea,
  type Column,
  type SelectOption
} from '@/components/common'
import {
  type Candidate,
  type DeptTreeNode,
  type Interview,
  type PositionOption,
  type RecruitmentRequest,
  approveRecruitmentRequest,
  cancelInterview,
  cancelRecruitmentRequest,
  completeInterview,
  completeRecruitmentRequest,
  createCandidate,
  createRecruitmentRequest,
  getDeptTreeOptions,
  getPositionOptions,
  listCandidates,
  listInterviews,
  listRecruitmentRequests,
  scheduleInterview,
  submitRecruitmentRequest,
  updateCandidateStatus
} from '@/services/api/hr'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errorMessage'
import {
  candidateSourceLabel,
  formatCurrency,
  formatDate,
  normalizeRows,
  parseAttachmentText,
  statusTone,
  todayValue,
  workflowStatusLabel,
  flattenDeptTree
} from './hrUtils'

type TabKey = 'requests' | 'candidates' | 'interviews'
type DialogMode = 'request' | 'candidate' | 'interview' | 'evaluation' | null

const toast = useToastStore()
const loading = ref(false)
const submitting = ref(false)
const tab = ref<TabKey>('requests')
const dialogMode = ref<DialogMode>(null)
const keyword = ref('')
const selectedInterviewId = ref<number | null>(null)
const requests = ref<RecruitmentRequest[]>([])
const candidates = ref<Candidate[]>([])
const interviews = ref<Interview[]>([])
const deptOptions = ref<DeptTreeNode[]>([])
const positionOptions = ref<PositionOption[]>([])

const requestForm = ref({
  deptId: '',
  positionId: '',
  headcount: '1',
  jobRequirements: '',
  salaryMin: '',
  salaryMax: '',
  expectedDate: todayValue()
})

const candidateForm = ref({
  requestId: '',
  name: '',
  gender: 'MALE',
  phone: '',
  email: '',
  source: 'WEBSITE',
  resumeValue: ''
})

const interviewForm = ref({
  candidateId: '',
  interviewRound: 'FIRST',
  interviewType: 'ONSITE',
  interviewTime: '',
  location: '',
  interviewerIds: ''
})

const evaluationForm = ref({
  evaluation: '',
  score: '80',
  result: 'PASSED'
})

const requestColumns: Column<RecruitmentRequest>[] = [
  { key: 'requestNo', label: '需求编号' },
  { key: 'deptName', label: '招聘岗位' },
  { key: 'headcount', label: '人数', sortable: true },
  { key: 'salaryMin', label: '薪资范围' },
  { key: 'status', label: '状态' },
  { key: 'expectedDate', label: '期望到岗' },
  { key: 'actions', label: '操作', class: 'text-right' }
]

const candidateColumns: Column<Candidate>[] = [
  { key: 'name', label: '候选人' },
  { key: 'positionName', label: '岗位' },
  { key: 'source', label: '来源' },
  { key: 'status', label: '状态' },
  { key: 'createTime', label: '创建时间' },
  { key: 'actions', label: '操作', class: 'text-right' }
]

const interviewColumns: Column<Interview>[] = [
  { key: 'candidateName', label: '候选人' },
  { key: 'interviewRound', label: '轮次' },
  { key: 'interviewTime', label: '时间地点' },
  { key: 'interviewerNames', label: '面试官' },
  { key: 'status', label: '状态' },
  { key: 'actions', label: '操作', class: 'text-right' }
]

const genderOptions: SelectOption[] = [
  { value: 'MALE', label: '男' },
  { value: 'FEMALE', label: '女' }
]

const sourceOptions: SelectOption[] = Object.entries(candidateSourceLabel).map(([value, label]) => ({ value, label }))
const roundOptions: SelectOption[] = [
  { value: 'FIRST', label: '初试' },
  { value: 'SECOND', label: '复试' },
  { value: 'FINAL', label: '终试' }
]
const interviewTypeOptions: SelectOption[] = [
  { value: 'ONSITE', label: '现场面试' },
  { value: 'ONLINE', label: '在线视频' },
  { value: 'PHONE', label: '电话面试' }
]
const resultOptions: SelectOption[] = [
  { value: 'PASSED', label: '通过' },
  { value: 'FAILED', label: '未通过' }
]

const deptSelectOptions = computed<SelectOption[]>(() =>
  flattenDeptTree(deptOptions.value).map((item) => ({ value: item.deptId, label: item.deptName }))
)
const positionSelectOptions = computed<SelectOption[]>(() =>
  positionOptions.value.map((item) => ({ value: item.id || item.positionId || 0, label: item.positionName }))
)
const requestSelectOptions = computed<SelectOption[]>(() =>
  requests.value.map((item) => ({
    value: item.id,
    label: `${item.requestNo || item.id} · ${item.deptName || '-'} / ${item.positionName || '-'}`
  }))
)
const candidateSelectOptions = computed<SelectOption[]>(() =>
  candidates.value.map((item) => ({ value: item.id, label: `${item.name} · ${item.positionName || item.requestNo || '-'}` }))
)

const filteredRequests = computed(() => {
  const q = keyword.value.trim().toLowerCase()
  if (!q) return requests.value
  return requests.value.filter((item) =>
    [item.requestNo, item.deptName, item.positionName, item.statusDesc, item.status].some((value) =>
      String(value || '').toLowerCase().includes(q)
    )
  )
})

const filteredCandidates = computed(() => {
  const q = keyword.value.trim().toLowerCase()
  if (!q) return candidates.value
  return candidates.value.filter((item) =>
    [item.name, item.phone, item.email, item.positionName, item.statusDesc, item.status].some((value) =>
      String(value || '').toLowerCase().includes(q)
    )
  )
})

const summary = computed(() => ({
  requests: requests.value.length,
  candidates: candidates.value.length,
  interviews: interviews.value.length,
  active: requests.value.filter((item) => ['APPROVED', 'RECRUITING', 'ACTIVE'].includes(String(item.status || '').toUpperCase())).length
}))

const loadOptions = async () => {
  const [deptRes, positionRes] = await Promise.allSettled([getDeptTreeOptions(), getPositionOptions()])
  deptOptions.value = deptRes.status === 'fulfilled' ? normalizeRows<DeptTreeNode>(deptRes.value) : []
  positionOptions.value = positionRes.status === 'fulfilled' ? normalizeRows<PositionOption>(positionRes.value) : []
}

const loadData = async () => {
  loading.value = true
  try {
    const [requestRes, candidateRes, interviewRes] = await Promise.all([
      listRecruitmentRequests({ pageNum: 1, pageSize: 200 }),
      listCandidates({ pageNum: 1, pageSize: 200 }),
      listInterviews({ pageNum: 1, pageSize: 200 })
    ])
    requests.value = normalizeRows<RecruitmentRequest>(requestRes)
    candidates.value = normalizeRows<Candidate>(candidateRes)
    interviews.value = normalizeRows<Interview>(interviewRes)
  } catch (error) {
    toast.error(getErrorMessage(error, '招聘数据加载失败'))
  } finally {
    loading.value = false
  }
}

const openRequestDialog = () => {
  requestForm.value = {
    deptId: String(deptSelectOptions.value[0]?.value || ''),
    positionId: String(positionSelectOptions.value[0]?.value || ''),
    headcount: '1',
    jobRequirements: '',
    salaryMin: '',
    salaryMax: '',
    expectedDate: todayValue()
  }
  dialogMode.value = 'request'
}

const openCandidateDialog = () => {
  candidateForm.value = {
    requestId: String(requestSelectOptions.value[0]?.value || ''),
    name: '',
    gender: 'MALE',
    phone: '',
    email: '',
    source: 'WEBSITE',
    resumeValue: ''
  }
  dialogMode.value = 'candidate'
}

const openInterviewDialog = () => {
  interviewForm.value = {
    candidateId: String(candidateSelectOptions.value[0]?.value || ''),
    interviewRound: 'FIRST',
    interviewType: 'ONSITE',
    interviewTime: '',
    location: '',
    interviewerIds: ''
  }
  dialogMode.value = 'interview'
}

const openEvaluationDialog = (id: number) => {
  selectedInterviewId.value = id
  evaluationForm.value = { evaluation: '', score: '80', result: 'PASSED' }
  dialogMode.value = 'evaluation'
}

const parseIds = (value: string) =>
  value.split(/[,，\s]+/).map((item) => Number(item)).filter((item) => Number.isFinite(item) && item > 0)

const handleSave = async () => {
  submitting.value = true
  try {
    if (dialogMode.value === 'request') {
      await createRecruitmentRequest({
        deptId: Number(requestForm.value.deptId),
        positionId: Number(requestForm.value.positionId),
        headcount: Number(requestForm.value.headcount || 1),
        jobRequirements: requestForm.value.jobRequirements,
        salaryMin: requestForm.value.salaryMin ? Number(requestForm.value.salaryMin) : undefined,
        salaryMax: requestForm.value.salaryMax ? Number(requestForm.value.salaryMax) : undefined,
        expectedDate: requestForm.value.expectedDate || undefined
      })
    } else if (dialogMode.value === 'candidate') {
      await createCandidate({
        requestId: candidateForm.value.requestId ? Number(candidateForm.value.requestId) : undefined,
        name: candidateForm.value.name,
        gender: candidateForm.value.gender,
        phone: candidateForm.value.phone,
        email: candidateForm.value.email,
        source: candidateForm.value.source,
        resumeAttachmentUrls: parseAttachmentText(candidateForm.value.resumeValue)
      })
    } else if (dialogMode.value === 'interview') {
      await scheduleInterview({
        candidateId: Number(interviewForm.value.candidateId),
        interviewRound: interviewForm.value.interviewRound,
        interviewType: interviewForm.value.interviewType,
        interviewTime: interviewForm.value.interviewTime,
        location: interviewForm.value.location,
        interviewerIds: parseIds(interviewForm.value.interviewerIds)
      })
    } else if (dialogMode.value === 'evaluation' && selectedInterviewId.value) {
      await completeInterview(selectedInterviewId.value, {
        evaluation: evaluationForm.value.evaluation,
        score: Number(evaluationForm.value.score || 0),
        result: evaluationForm.value.result
      })
    }
    dialogMode.value = null
    toast.success('保存成功')
    await loadData()
  } catch (error) {
    toast.error(getErrorMessage(error, '保存失败'))
  } finally {
    submitting.value = false
  }
}

const runAction = async (action: () => Promise<unknown>, message: string) => {
  submitting.value = true
  try {
    await action()
    toast.success(message)
    await loadData()
  } catch (error) {
    toast.error(getErrorMessage(error, '操作失败'))
  } finally {
    submitting.value = false
  }
}

onMounted(async () => {
  await Promise.all([loadOptions(), loadData()])
})
</script>

<template>
  <div class="space-y-4">
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div>
        <div class="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.16em] text-slate-400 dark:text-slate-500">
          <Briefcase class="h-3.5 w-3.5 text-cyan-600 dark:text-cyan-300" />
          Recruiting Pipeline
        </div>
        <h1 class="mt-1.5 text-[26px] font-semibold tracking-tight text-slate-900 dark:text-slate-100">招聘管理</h1>
      </div>
      <Button variant="outline" :disabled="loading" @click="loadData">
        <RefreshCcw class="h-4 w-4" :class="loading ? 'animate-spin' : ''" />
        刷新
      </Button>
    </div>

    <div class="grid gap-4 md:grid-cols-4">
      <div class="card p-4"><div class="text-xs text-slate-500">招聘需求</div><div class="mt-2 text-2xl font-semibold">{{ summary.requests }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">候选人</div><div class="mt-2 text-2xl font-semibold">{{ summary.candidates }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">面试安排</div><div class="mt-2 text-2xl font-semibold">{{ summary.interviews }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">进行中需求</div><div class="mt-2 text-2xl font-semibold">{{ summary.active }}</div></div>
    </div>

    <div class="flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm dark:border-slate-800 dark:bg-slate-950/80">
      <Button :variant="tab === 'requests' ? 'primary' : 'outline'" size="sm" @click="tab = 'requests'">招聘需求</Button>
      <Button :variant="tab === 'candidates' ? 'primary' : 'outline'" size="sm" @click="tab = 'candidates'">候选人</Button>
      <Button :variant="tab === 'interviews' ? 'primary' : 'outline'" size="sm" @click="tab = 'interviews'">面试</Button>
    </div>

    <Panel v-if="tab === 'requests'" title="招聘需求">
      <template #icon><ClipboardCheck class="h-4 w-4 text-slate-500" /></template>
      <template #actions><Button size="sm" @click="openRequestDialog"><Plus class="h-3.5 w-3.5" />新建需求</Button></template>
      <div class="mb-4 max-w-md"><Input v-model="keyword" placeholder="搜索需求、部门、职位、状态" /></div>
      <DataTable :columns="requestColumns" :data="filteredRequests" :loading="loading" row-key="id">
        <template #cell-deptName="{ row }">
          <div class="font-semibold">{{ row.deptName || '-' }}</div>
          <div class="text-xs text-slate-500">{{ row.positionName || '-' }}</div>
        </template>
        <template #cell-salaryMin="{ row }">{{ formatCurrency(row.salaryMin) }} - {{ formatCurrency(row.salaryMax) }}</template>
        <template #cell-status="{ row }"><StatusBadge :label="row.statusDesc || workflowStatusLabel[row.status || ''] || row.status || '-'" :tone="statusTone(row.status)" /></template>
        <template #cell-expectedDate="{ row }">{{ formatDate(row.expectedDate) }}</template>
        <template #cell-actions="{ row }">
          <div class="flex justify-end gap-1">
            <Button size="sm" variant="outline" @click="runAction(() => submitRecruitmentRequest(row.id), '已提交')">提交</Button>
            <Button size="sm" variant="outline" @click="runAction(() => approveRecruitmentRequest(row.id), '已审批')">审批</Button>
            <Button size="sm" @click="runAction(() => completeRecruitmentRequest(row.id), '已完成')">完成</Button>
            <Button size="icon" variant="ghost" @click="runAction(() => cancelRecruitmentRequest(row.id), '已取消')"><XCircle class="h-4 w-4" /></Button>
          </div>
        </template>
      </DataTable>
    </Panel>

    <Panel v-else-if="tab === 'candidates'" title="候选人">
      <template #icon><UserRoundSearch class="h-4 w-4 text-slate-500" /></template>
      <template #actions><Button size="sm" @click="openCandidateDialog"><Plus class="h-3.5 w-3.5" />新增候选人</Button></template>
      <div class="mb-4 max-w-md"><Input v-model="keyword" placeholder="搜索姓名、电话、邮箱、职位" /></div>
      <DataTable :columns="candidateColumns" :data="filteredCandidates" :loading="loading" row-key="id">
        <template #cell-name="{ row }">
          <div class="font-semibold">{{ row.name }}</div>
          <div class="text-xs text-slate-500">{{ row.phone || row.email || '-' }}</div>
        </template>
        <template #cell-source="{ row }">{{ row.sourceDesc || candidateSourceLabel[row.source || ''] || row.source || '-' }}</template>
        <template #cell-status="{ row }"><StatusBadge :label="row.statusDesc || workflowStatusLabel[row.status || ''] || row.status || '-'" :tone="statusTone(row.status)" /></template>
        <template #cell-createTime="{ row }">{{ formatDate(row.createTime) }}</template>
        <template #cell-actions="{ row }">
          <div class="flex justify-end gap-1">
            <Button size="sm" variant="outline" @click="runAction(() => updateCandidateStatus(row.id, 'INTERVIEW'), '已进入面试')">面试</Button>
            <Button size="sm" @click="runAction(() => updateCandidateStatus(row.id, 'PASSED'), '已通过')">通过</Button>
            <Button size="icon" variant="ghost" @click="runAction(() => updateCandidateStatus(row.id, 'REJECTED', 'HR 操作拒绝'), '已拒绝')"><XCircle class="h-4 w-4" /></Button>
          </div>
        </template>
      </DataTable>
    </Panel>

    <Panel v-else title="面试安排">
      <template #icon><CalendarClock class="h-4 w-4 text-slate-500" /></template>
      <template #actions><Button size="sm" @click="openInterviewDialog"><Plus class="h-3.5 w-3.5" />安排面试</Button></template>
      <DataTable :columns="interviewColumns" :data="interviews" :loading="loading" row-key="id">
        <template #cell-interviewRound="{ row }">{{ row.interviewRoundName || row.interviewRound || '-' }}<div class="text-xs text-slate-500">{{ row.interviewTypeName || row.interviewType || '-' }}</div></template>
        <template #cell-interviewTime="{ row }">{{ row.interviewTime || '-' }}<div class="text-xs text-slate-500">{{ row.location || '-' }}</div></template>
        <template #cell-interviewerNames="{ row }">{{ row.interviewerNames?.join('、') || '-' }}</template>
        <template #cell-status="{ row }"><StatusBadge :label="row.statusName || workflowStatusLabel[row.status || ''] || row.status || '-'" :tone="statusTone(row.status)" /></template>
        <template #cell-actions="{ row }">
          <div class="flex justify-end gap-1">
            <Button size="icon" variant="ghost" @click="openEvaluationDialog(row.id)"><CheckCircle2 class="h-4 w-4" /></Button>
            <Button size="icon" variant="ghost" @click="runAction(() => cancelInterview(row.id), '已取消')"><XCircle class="h-4 w-4" /></Button>
          </div>
        </template>
      </DataTable>
    </Panel>

    <BaseDialog :show="Boolean(dialogMode)" title="招聘操作" width="wide" @close="dialogMode = null">
      <div v-if="dialogMode === 'request'" class="grid gap-4 md:grid-cols-2">
        <label class="space-y-2"><span class="text-sm font-medium">部门</span><Select v-model="requestForm.deptId" :options="deptSelectOptions" searchable /></label>
        <label class="space-y-2"><span class="text-sm font-medium">职位</span><Select v-model="requestForm.positionId" :options="positionSelectOptions" searchable /></label>
        <Input v-model="requestForm.headcount" label="招聘人数" type="number" />
        <Input v-model="requestForm.expectedDate" label="期望到岗" type="date" />
        <Input v-model="requestForm.salaryMin" label="薪资下限" type="number" />
        <Input v-model="requestForm.salaryMax" label="薪资上限" type="number" />
        <TextArea v-model="requestForm.jobRequirements" label="岗位要求" class="md:col-span-2" />
      </div>
      <div v-else-if="dialogMode === 'candidate'" class="grid gap-4 md:grid-cols-2">
        <label class="space-y-2"><span class="text-sm font-medium">关联需求</span><Select v-model="candidateForm.requestId" :options="requestSelectOptions" searchable /></label>
        <Input v-model="candidateForm.name" label="姓名" required />
        <label class="space-y-2"><span class="text-sm font-medium">性别</span><Select v-model="candidateForm.gender" :options="genderOptions" /></label>
        <label class="space-y-2"><span class="text-sm font-medium">来源</span><Select v-model="candidateForm.source" :options="sourceOptions" /></label>
        <Input v-model="candidateForm.phone" label="手机号" />
        <Input v-model="candidateForm.email" label="邮箱" />
        <TextArea v-model="candidateForm.resumeValue" label="简历 URL（一行一个）" class="md:col-span-2" />
      </div>
      <div v-else-if="dialogMode === 'interview'" class="grid gap-4 md:grid-cols-2">
        <label class="space-y-2"><span class="text-sm font-medium">候选人</span><Select v-model="interviewForm.candidateId" :options="candidateSelectOptions" searchable /></label>
        <label class="space-y-2"><span class="text-sm font-medium">轮次</span><Select v-model="interviewForm.interviewRound" :options="roundOptions" /></label>
        <label class="space-y-2"><span class="text-sm font-medium">形式</span><Select v-model="interviewForm.interviewType" :options="interviewTypeOptions" /></label>
        <Input v-model="interviewForm.interviewTime" label="面试时间" type="datetime-local" />
        <Input v-model="interviewForm.location" label="地点/会议链接" />
        <Input v-model="interviewForm.interviewerIds" label="面试官用户ID（逗号分隔）" />
      </div>
      <div v-else-if="dialogMode === 'evaluation'" class="grid gap-4 md:grid-cols-2">
        <label class="space-y-2"><span class="text-sm font-medium">结果</span><Select v-model="evaluationForm.result" :options="resultOptions" /></label>
        <Input v-model="evaluationForm.score" label="评分" type="number" />
        <TextArea v-model="evaluationForm.evaluation" label="面试评价" class="md:col-span-2" />
      </div>
      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="dialogMode = null">取消</Button>
          <Button :disabled="submitting" @click="handleSave"><Save class="h-4 w-4" />保存</Button>
        </div>
      </template>
    </BaseDialog>
  </div>
</template>

// cloudflow-frontend/src/pages/hr/HrRecruitmentPage.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, CalendarRange, Plus, Search, UserRoundSearch } from 'lucide-react';
import { toast } from 'sonner';
import { Card, Button, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs, TabsContent, TabsList, TabsTrigger, Textarea } from '@/components/ui';
import { Candidate, CandidatePayload, DeptTreeNode, Interview, InterviewSchedulePayload, PositionOption, RecruitmentRequest, RecruitmentRequestPayload, listRecruitmentRequests, createRecruitmentRequest, listCandidates, createCandidate, updateCandidateStatus, listInterviews, scheduleInterview, getDeptTreeOptions, getPositionOptions, submitRecruitmentRequest, approveRecruitmentRequest, completeRecruitmentRequest, cancelRecruitmentRequest } from '@/services/api/hr';

const normalizeRows = <T,>(data: any): T[] => {
  if (!data) return [];
  if (Array.isArray(data)) return data as T[];
  if (Array.isArray(data.records)) return data.records as T[];
  if (Array.isArray(data.rows)) return data.rows as T[];
  return [];
};

const flattenDeptTree = (nodes: DeptTreeNode[] = [], prefix = ''): Array<{ label: string; value: number }> => {
  const result: Array<{ label: string; value: number }> = [];
  nodes.forEach(node => {
    result.push({ label: prefix ? `${prefix} / ${node.deptName}` : node.deptName, value: node.deptId });
    if (node.children?.length) {
      result.push(...flattenDeptTree(node.children, prefix ? `${prefix} / ${node.deptName}` : node.deptName));
    }
  });
  return result;
};

const requestStatusTone: Record<string, string> = {
  DRAFT: 'bg-slate-100 text-slate-700',
  APPROVING: 'bg-amber-50 text-amber-700',
  RECRUITING: 'bg-emerald-50 text-emerald-700',
  COMPLETED: 'bg-slate-100 text-slate-600',
  CANCELLED: 'bg-rose-50 text-rose-700',
};

const candidateStatusTone: Record<string, string> = {
  NEW: 'bg-slate-100 text-slate-700',
  SCREENING: 'bg-blue-50 text-blue-700',
  INTERVIEW: 'bg-amber-50 text-amber-700',
  OFFER: 'bg-pink-50 text-pink-700',
  HIRED: 'bg-emerald-50 text-emerald-700',
  REJECTED: 'bg-rose-50 text-rose-700',
};

const interviewStatusTone: Record<string, string> = {
  SCHEDULED: 'bg-blue-50 text-blue-700',
  COMPLETED: 'bg-emerald-50 text-emerald-700',
  CANCELLED: 'bg-slate-100 text-slate-700',
};

const requestFormDefault: RecruitmentRequestPayload = {
  deptId: 103,
  positionId: 0,
  headcount: 1,
  jobRequirements: '',
  salaryMin: 15000,
  salaryMax: 25000,
  expectedDate: '',
};

const candidateFormDefault: CandidatePayload = {
  requestId: 0,
  name: '',
  gender: 'MALE',
  phone: '',
  email: '',
  resumeUrl: '',
  source: 'WEBSITE',
};

const interviewFormDefault: InterviewSchedulePayload = {
  candidateId: 0,
  interviewRound: 'FIRST',
  interviewType: 'VIDEO',
  interviewTime: '',
  location: '',
  interviewerIds: [],
};

export const HrRecruitmentPage: React.FC = () => {
  const [requests, setRequests] = useState<RecruitmentRequest[]>([]);
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [interviews, setInterviews] = useState<Interview[]>([]);
  const [deptOptions, setDeptOptions] = useState<Array<{ label: string; value: number }>>([]);
  const [positionOptions, setPositionOptions] = useState<PositionOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [keyword, setKeyword] = useState('');
  const [requestDialog, setRequestDialog] = useState(false);
  const [candidateDialog, setCandidateDialog] = useState(false);
  const [interviewDialog, setInterviewDialog] = useState(false);
  const [rejectCandidateId, setRejectCandidateId] = useState<number | null>(null);
  const [rejectReason, setRejectReason] = useState('');
  const [requestForm, setRequestForm] = useState<RecruitmentRequestPayload>(requestFormDefault);
  const [candidateForm, setCandidateForm] = useState<CandidatePayload>(candidateFormDefault);
  const [interviewForm, setInterviewForm] = useState<InterviewSchedulePayload>(interviewFormDefault);

  const loadData = async () => {
    setLoading(true);
    try {
      const [requestRes, candidateRes, interviewRes, deptRes, positionRes] = await Promise.all([
        listRecruitmentRequests({ pageNum: 1, pageSize: 50 }),
        listCandidates({ pageNum: 1, pageSize: 50 }),
        listInterviews(),
        getDeptTreeOptions(),
        getPositionOptions(),
      ]);
      setRequests(normalizeRows<RecruitmentRequest>(requestRes));
      setCandidates(normalizeRows<Candidate>(candidateRes));
      setInterviews(normalizeRows<Interview>(interviewRes));
      setDeptOptions(flattenDeptTree(Array.isArray(deptRes) ? deptRes : []));
      setPositionOptions(Array.isArray(positionRes) ? positionRes : []);
    } catch (error) {
      console.error(error);
      toast.error('招聘数据加载失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadData();
  }, []);

  useEffect(() => {
    if (positionOptions.length && !requestForm.positionId) {
      setRequestForm(prev => ({ ...prev, positionId: positionOptions[0].id }));
    }
    if (candidates.length && !interviewForm.candidateId) {
      setInterviewForm(prev => ({ ...prev, candidateId: candidates[0].id }));
    }
  }, [positionOptions, candidates, requestForm.positionId, interviewForm.candidateId]);

  const filteredRequests = useMemo(
    () => requests.filter(item => [item.requestNo, item.positionName, item.deptName, item.jobRequirements].filter(Boolean).some(value => String(value).toLowerCase().includes(keyword.toLowerCase()))),
    [requests, keyword],
  );
  const recruitingRequests = useMemo(
    () => requests.filter(item => item.status === 'RECRUITING'),
    [requests],
  );

  const filteredCandidates = useMemo(
    () => candidates.filter(item => [item.name, item.phone, item.email, item.positionName, item.statusDesc].filter(Boolean).some(value => String(value).toLowerCase().includes(keyword.toLowerCase()))),
    [candidates, keyword],
  );

  useEffect(() => {
    if (recruitingRequests.length && !candidateForm.requestId) {
      setCandidateForm(prev => ({ ...prev, requestId: recruitingRequests[0].id }));
      return;
    }

    if (candidateForm.requestId && !recruitingRequests.some(item => item.id === candidateForm.requestId)) {
      setCandidateForm(prev => ({ ...prev, requestId: recruitingRequests[0]?.id || 0 }));
    }
  }, [candidateForm.requestId, recruitingRequests]);

  const handleCreateRequest = async () => {
    try {
      await createRecruitmentRequest(requestForm);
      toast.success('招聘需求已创建');
      setRequestDialog(false);
      setRequestForm(requestFormDefault);
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '招聘需求创建失败');
    }
  };

  const handleSubmitRequest = async (id: number) => {
    try {
      await submitRecruitmentRequest(id);
      toast.success('招聘需求已提交');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '招聘需求提交失败');
    }
  };

  const handleApproveRequest = async (id: number) => {
    try {
      await approveRecruitmentRequest(id);
      toast.success('招聘需求已审批通过');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '招聘需求审批失败');
    }
  };

  const handleCompleteRequest = async (id: number) => {
    try {
      await completeRecruitmentRequest(id);
      toast.success('招聘需求已完成');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '招聘需求完成失败');
    }
  };

  const handleCancelRequest = async (id: number) => {
    try {
      await cancelRecruitmentRequest(id);
      toast.success('招聘需求已取消');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '招聘需求取消失败');
    }
  };

  const handleCreateCandidate = async () => {
    try {
      await createCandidate(candidateForm);
      toast.success('候选人已录入');
      setCandidateDialog(false);
      setCandidateForm(candidateFormDefault);
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '候选人创建失败');
    }
  };

  const handleScheduleInterview = async () => {
    try {
      await scheduleInterview(interviewForm);
      toast.success('面试已安排');
      setInterviewDialog(false);
      setInterviewForm(interviewFormDefault);
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '面试安排失败');
    }
  };

  const handleCandidateStatusChange = async (id: number, status: string) => {
    if (status === 'REJECTED') {
      setRejectCandidateId(id);
      setRejectReason('');
      return;
    }

    try {
      await updateCandidateStatus(id, status);
      toast.success('候选人状态已更新');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '候选人状态更新失败');
    }
  };

  const handleRejectCandidate = async () => {
    if (!rejectCandidateId) return;
    if (!rejectReason.trim()) {
      toast.error('请输入拒绝原因');
      return;
    }

    try {
      await updateCandidateStatus(rejectCandidateId, 'REJECTED', rejectReason.trim());
      toast.success('候选人已标记为拒绝');
      setRejectCandidateId(null);
      setRejectReason('');
      await loadData();
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '候选人状态更新失败');
    }
  };

  return (
    <div className="space-y-6">
      <Card className="rounded-3xl border-white/80 bg-white/70 p-8 shadow-[0_12px_40px_rgba(15,23,42,0.06)] backdrop-blur-xl">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-600">
              <BriefcaseBusiness size={14} />
              Recruitment Hub
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-slate-900">招聘与候选人中心</h1>
            <p className="mt-2 text-sm text-slate-500">把招聘需求、候选人推进和面试安排放在一个桌面工作区。</p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button className="rounded-2xl" onClick={() => setRequestDialog(true)}>
              <Plus size={16} className="mr-2" />
              新建招聘需求
            </Button>
            <Button variant="outline" className="rounded-2xl" onClick={() => setCandidateDialog(true)}>
              <UserRoundSearch size={16} className="mr-2" />
              新建候选人
            </Button>
            <Button variant="outline" className="rounded-2xl" onClick={() => setInterviewDialog(true)}>
              <CalendarRange size={16} className="mr-2" />
              安排面试
            </Button>
          </div>
        </div>
      </Card>

      <Card className="rounded-3xl border-white/80 bg-white/70 p-5 backdrop-blur-xl">
        <div className="relative">
          <Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <Input className="pl-10" placeholder="搜索需求编号、岗位、候选人、邮箱或状态" value={keyword} onChange={event => setKeyword(event.target.value)} />
        </div>
      </Card>

      <Tabs defaultValue="request">
        <TabsList className="grid w-full grid-cols-3 rounded-2xl bg-white/70 p-1 backdrop-blur-xl">
          <TabsTrigger value="request">招聘需求</TabsTrigger>
          <TabsTrigger value="candidate">候选人</TabsTrigger>
          <TabsTrigger value="interview">面试安排</TabsTrigger>
        </TabsList>

        <TabsContent value="request" className="mt-4">
          <Card className="rounded-3xl border-white/80 bg-white/70 p-2 backdrop-blur-xl">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>需求编号</TableHead>
                  <TableHead>部门</TableHead>
                  <TableHead>岗位</TableHead>
                  <TableHead>招聘人数</TableHead>
                  <TableHead>已录用</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead className="text-right">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredRequests.map(item => (
                  <TableRow key={item.id}>
                    <TableCell className="font-semibold text-slate-900">{item.requestNo}</TableCell>
                    <TableCell>{item.deptName || '-'}</TableCell>
                    <TableCell>{item.positionName || '-'}</TableCell>
                    <TableCell>{item.headcount}</TableCell>
                    <TableCell>{item.hiredCount}</TableCell>
                    <TableCell><span className={`rounded-full px-2 py-1 text-xs font-medium ${requestStatusTone[item.status] || requestStatusTone.DRAFT}`}>{item.statusDesc || item.status}</span></TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" disabled={item.status !== 'DRAFT'} onClick={() => void handleSubmitRequest(item.id)}>
                          提交
                        </Button>
                        <Button size="sm" variant="outline" disabled={item.status !== 'APPROVING'} onClick={() => void handleApproveRequest(item.id)}>
                          审批通过
                        </Button>
                        <Button size="sm" variant="outline" disabled={item.status !== 'RECRUITING'} onClick={() => void handleCompleteRequest(item.id)}>
                          完成
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={item.status === 'COMPLETED' || item.status === 'CANCELLED'}
                          onClick={() => void handleCancelRequest(item.id)}
                        >
                          取消
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
                {!filteredRequests.length && !loading && (
                  <TableRow>
                    <TableCell colSpan={7} className="py-12 text-center text-slate-400">暂无招聘需求</TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </Card>
        </TabsContent>

        <TabsContent value="candidate" className="mt-4">
          <Card className="rounded-3xl border-white/80 bg-white/70 p-2 backdrop-blur-xl">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>候选人</TableHead>
                  <TableHead>手机号</TableHead>
                  <TableHead>来源</TableHead>
                  <TableHead>岗位</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead className="text-right">推进</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredCandidates.map(item => (
                  <TableRow key={item.id}>
                    <TableCell>
                      <div className="font-semibold text-slate-900">{item.name}</div>
                      <div className="text-xs text-slate-400">{item.email || '-'}</div>
                    </TableCell>
                    <TableCell>{item.phone}</TableCell>
                    <TableCell>{item.sourceDesc || item.source || '-'}</TableCell>
                    <TableCell>{item.positionName || '-'}</TableCell>
                    <TableCell><span className={`rounded-full px-2 py-1 text-xs font-medium ${candidateStatusTone[item.status] || candidateStatusTone.NEW}`}>{item.statusDesc || item.status}</span></TableCell>
                    <TableCell className="text-right">
                      <Select value={item.status} onValueChange={value => handleCandidateStatusChange(item.id, value)}>
                        <SelectTrigger className="ml-auto w-[140px]">
                          <SelectValue placeholder="更新状态" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="NEW">新简历</SelectItem>
                          <SelectItem value="SCREENING">筛选中</SelectItem>
                          <SelectItem value="INTERVIEW">面试中</SelectItem>
                          <SelectItem value="OFFER">Offer</SelectItem>
                          <SelectItem value="HIRED">已入职</SelectItem>
                          <SelectItem value="REJECTED">已拒绝</SelectItem>
                        </SelectContent>
                      </Select>
                    </TableCell>
                  </TableRow>
                ))}
                {!filteredCandidates.length && !loading && (
                  <TableRow>
                    <TableCell colSpan={6} className="py-12 text-center text-slate-400">暂无候选人记录</TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </Card>
        </TabsContent>

        <TabsContent value="interview" className="mt-4">
          <Card className="rounded-3xl border-white/80 bg-white/70 p-2 backdrop-blur-xl">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>候选人</TableHead>
                  <TableHead>轮次</TableHead>
                  <TableHead>形式</TableHead>
                  <TableHead>时间</TableHead>
                  <TableHead>地点</TableHead>
                  <TableHead>状态</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {interviews.map(item => (
                  <TableRow key={item.id}>
                    <TableCell className="font-semibold text-slate-900">{item.candidateName || '-'}</TableCell>
                    <TableCell>{item.interviewRoundName || item.interviewRound}</TableCell>
                    <TableCell>{item.interviewTypeName || item.interviewType}</TableCell>
                    <TableCell>{item.interviewTime}</TableCell>
                    <TableCell>{item.location || '-'}</TableCell>
                    <TableCell><span className={`rounded-full px-2 py-1 text-xs font-medium ${interviewStatusTone[item.status] || interviewStatusTone.SCHEDULED}`}>{item.statusName || item.status}</span></TableCell>
                  </TableRow>
                ))}
                {!interviews.length && !loading && (
                  <TableRow>
                    <TableCell colSpan={6} className="py-12 text-center text-slate-400">暂无面试安排</TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </Card>
        </TabsContent>
      </Tabs>

      {requestDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
          <div className="w-full max-w-2xl rounded-3xl border border-white/80 bg-white p-6 shadow-2xl">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-xl font-semibold text-slate-900">新建招聘需求</h2>
              <Button variant="ghost" onClick={() => setRequestDialog(false)}>关闭</Button>
            </div>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <Label>部门</Label>
                <Select value={String(requestForm.deptId)} onValueChange={value => setRequestForm(prev => ({ ...prev, deptId: Number(value) }))}>
                  <SelectTrigger><SelectValue placeholder="请选择部门" /></SelectTrigger>
                  <SelectContent>{deptOptions.map(option => <SelectItem key={option.value} value={String(option.value)}>{option.label}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div>
                <Label>职位</Label>
                <Select value={requestForm.positionId ? String(requestForm.positionId) : undefined} onValueChange={value => setRequestForm(prev => ({ ...prev, positionId: Number(value) }))}>
                  <SelectTrigger><SelectValue placeholder="请选择职位" /></SelectTrigger>
                  <SelectContent>{positionOptions.map(option => <SelectItem key={option.id} value={String(option.id)}>{option.positionName}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div><Label>招聘人数</Label><Input type="number" min={1} value={requestForm.headcount} onChange={event => setRequestForm(prev => ({ ...prev, headcount: Number(event.target.value) || 1 }))} /></div>
              <div><Label>期望到岗日期</Label><Input type="date" value={requestForm.expectedDate || ''} onChange={event => setRequestForm(prev => ({ ...prev, expectedDate: event.target.value }))} /></div>
              <div><Label>薪资下限</Label><Input type="number" value={requestForm.salaryMin || ''} onChange={event => setRequestForm(prev => ({ ...prev, salaryMin: Number(event.target.value) || undefined }))} /></div>
              <div><Label>薪资上限</Label><Input type="number" value={requestForm.salaryMax || ''} onChange={event => setRequestForm(prev => ({ ...prev, salaryMax: Number(event.target.value) || undefined }))} /></div>
              <div className="md:col-span-2"><Label>任职要求</Label><Input value={requestForm.jobRequirements || ''} onChange={event => setRequestForm(prev => ({ ...prev, jobRequirements: event.target.value }))} /></div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <Button variant="outline" onClick={() => setRequestDialog(false)}>取消</Button>
              <Button onClick={handleCreateRequest}>创建需求</Button>
            </div>
          </div>
        </div>
      )}

      {candidateDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
          <div className="w-full max-w-2xl rounded-3xl border border-white/80 bg-white p-6 shadow-2xl">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-xl font-semibold text-slate-900">录入候选人</h2>
              <Button variant="ghost" onClick={() => setCandidateDialog(false)}>关闭</Button>
            </div>
            {!recruitingRequests.length && (
              <div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">
                当前没有“招聘中”的需求。请先在需求列表完成提交和审批通过，再录入候选人。
              </div>
            )}
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <Label>关联招聘需求</Label>
                <Select value={candidateForm.requestId ? String(candidateForm.requestId) : undefined} onValueChange={value => setCandidateForm(prev => ({ ...prev, requestId: Number(value) }))}>
                  <SelectTrigger><SelectValue placeholder="请选择需求" /></SelectTrigger>
                  <SelectContent>{recruitingRequests.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.requestNo} / {item.positionName || item.positionId}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div><Label>姓名</Label><Input value={candidateForm.name} onChange={event => setCandidateForm(prev => ({ ...prev, name: event.target.value }))} /></div>
              <div>
                <Label>性别</Label>
                <Select value={candidateForm.gender || 'MALE'} onValueChange={value => setCandidateForm(prev => ({ ...prev, gender: value }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent><SelectItem value="MALE">男</SelectItem><SelectItem value="FEMALE">女</SelectItem></SelectContent>
                </Select>
              </div>
              <div><Label>手机号</Label><Input value={candidateForm.phone} onChange={event => setCandidateForm(prev => ({ ...prev, phone: event.target.value }))} /></div>
              <div><Label>邮箱</Label><Input value={candidateForm.email || ''} onChange={event => setCandidateForm(prev => ({ ...prev, email: event.target.value }))} /></div>
              <div>
                <Label>来源</Label>
                <Select value={candidateForm.source || 'WEBSITE'} onValueChange={value => setCandidateForm(prev => ({ ...prev, source: value }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="WEBSITE">官网</SelectItem>
                    <SelectItem value="REFERRAL">内推</SelectItem>
                    <SelectItem value="HEADHUNTER">猎头</SelectItem>
                    <SelectItem value="CAMPUS">校招</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="md:col-span-2"><Label>简历链接</Label><Input value={candidateForm.resumeUrl || ''} onChange={event => setCandidateForm(prev => ({ ...prev, resumeUrl: event.target.value }))} /></div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <Button variant="outline" onClick={() => setCandidateDialog(false)}>取消</Button>
              <Button disabled={!recruitingRequests.length || !candidateForm.requestId} onClick={handleCreateCandidate}>录入候选人</Button>
            </div>
          </div>
        </div>
      )}

      {interviewDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
          <div className="w-full max-w-2xl rounded-3xl border border-white/80 bg-white p-6 shadow-2xl">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-xl font-semibold text-slate-900">安排面试</h2>
              <Button variant="ghost" onClick={() => setInterviewDialog(false)}>关闭</Button>
            </div>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <Label>候选人</Label>
                <Select value={interviewForm.candidateId ? String(interviewForm.candidateId) : undefined} onValueChange={value => setInterviewForm(prev => ({ ...prev, candidateId: Number(value) }))}>
                  <SelectTrigger><SelectValue placeholder="请选择候选人" /></SelectTrigger>
                  <SelectContent>{candidates.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name} / {item.positionName || '-'}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div>
                <Label>轮次</Label>
                <Select value={interviewForm.interviewRound} onValueChange={value => setInterviewForm(prev => ({ ...prev, interviewRound: value }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent><SelectItem value="FIRST">初试</SelectItem><SelectItem value="SECOND">复试</SelectItem><SelectItem value="FINAL">终面</SelectItem></SelectContent>
                </Select>
              </div>
              <div>
                <Label>面试形式</Label>
                <Select value={interviewForm.interviewType} onValueChange={value => setInterviewForm(prev => ({ ...prev, interviewType: value }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent><SelectItem value="PHONE">电话面试</SelectItem><SelectItem value="VIDEO">视频面试</SelectItem><SelectItem value="ONSITE">现场面试</SelectItem></SelectContent>
                </Select>
              </div>
              <div><Label>面试时间</Label><Input type="datetime-local" value={interviewForm.interviewTime} onChange={event => setInterviewForm(prev => ({ ...prev, interviewTime: event.target.value }))} /></div>
              <div className="md:col-span-2"><Label>地点 / 链接</Label><Input value={interviewForm.location || ''} onChange={event => setInterviewForm(prev => ({ ...prev, location: event.target.value }))} placeholder="会议室 / Teams 链接" /></div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <Button variant="outline" onClick={() => setInterviewDialog(false)}>取消</Button>
              <Button onClick={handleScheduleInterview}>安排面试</Button>
            </div>
          </div>
        </div>
      )}

      {rejectCandidateId !== null && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
          <div className="w-full max-w-xl rounded-3xl border border-white/80 bg-white p-6 shadow-2xl">
            <div className="mb-6 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-slate-900">填写拒绝原因</h2>
                <p className="mt-1 text-sm text-slate-500">候选人标记为“已拒绝”时，后端要求必须填写原因。</p>
              </div>
              <Button
                variant="ghost"
                onClick={() => {
                  setRejectCandidateId(null);
                  setRejectReason('');
                }}
              >
                关闭
              </Button>
            </div>
            <div>
              <Label>拒绝原因</Label>
              <Textarea
                className="mt-2"
                rows={4}
                value={rejectReason}
                onChange={event => setRejectReason(event.target.value)}
                placeholder="请输入候选人拒绝原因"
              />
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <Button
                variant="outline"
                onClick={() => {
                  setRejectCandidateId(null);
                  setRejectReason('');
                }}
              >
                取消
              </Button>
              <Button onClick={() => void handleRejectCandidate()}>确认拒绝</Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default HrRecruitmentPage;
