// cloudflow-frontend-vue/src/layouts/MobileLayout.vue
<script setup lang="ts">
import { Home, MessageSquare, PlayCircle, User } from 'lucide-vue-next'
import { useRoute } from 'vue-router'

const route = useRoute()
const tabs = [
  { path: '/dashboard', label: '首页', icon: Home },
  { path: '/workplace', label: '工作台', icon: PlayCircle },
  { path: '/announcement', label: '消息', icon: MessageSquare },
  { path: '/profile', label: '我的', icon: User }
]
</script>

<template>
  <div class="flex h-screen flex-col bg-slate-50 dark:bg-slate-950">
    <div class="flex-1 overflow-y-auto pb-16">
      <RouterView v-slot="{ Component, route: childRoute }">
        <Transition name="mobile-content-fade" mode="out-in">
          <component :is="Component" :key="childRoute.fullPath" />
        </Transition>
      </RouterView>
    </div>
    <nav class="fixed bottom-0 left-0 right-0 z-50 flex h-16 items-center justify-around border-t border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950" aria-label="主导航">
      <RouterLink
        v-for="tab in tabs"
        :key="tab.path"
        :to="tab.path"
        class="flex h-full w-full flex-col items-center justify-center text-slate-500"
        :class="route.path === tab.path ? 'text-teal-600 dark:text-teal-300' : ''"
      >
        <component :is="tab.icon" class="mb-1 h-6 w-6" />
        <span class="text-[10px] font-medium">{{ tab.label }}</span>
      </RouterLink>
    </nav>
  </div>
</template>

<style scoped>
.mobile-content-fade-enter-active,
.mobile-content-fade-leave-active {
  transition:
    opacity 0.2s ease,
    transform 0.2s ease;
}

.mobile-content-fade-enter-from {
  opacity: 0;
  transform: translateY(6px);
}

.mobile-content-fade-leave-to {
  opacity: 0;
  transform: translateY(-3px);
}

@media (prefers-reduced-motion: reduce) {
  .mobile-content-fade-enter-active,
  .mobile-content-fade-leave-active {
    transition: opacity 0.01s linear;
  }

  .mobile-content-fade-enter-from,
  .mobile-content-fade-leave-to {
    transform: none;
  }
}
</style>

// cloudflow-frontend/src/mobile/layouts/MobileLayout.tsx
import React from 'react';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { Home, PlayCircle, MessageSquare, User } from 'lucide-react';

export const MobileLayout: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const tabs = [
    { id: '/dashboard', label: '首页', icon: Home },
    { id: '/workplace', label: '工作台', icon: PlayCircle },
    { id: '/announcement', label: '消息', icon: MessageSquare },
    { id: '/profile', label: '我的', icon: User },
  ];

  return (
    <div className="flex flex-col h-screen bg-slate-50 font-[Inter]">
      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto pb-16">
        <Outlet />
      </div>

      {/* Bottom Tab Bar */}
      <nav 
        className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200 h-16 flex items-center justify-around z-50 pb-safe"
        role="navigation"
        aria-label="主导航"
      >
        {tabs.map((tab) => {
          const isActive = location.pathname === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => navigate(tab.id)}
              className="flex flex-col items-center justify-center w-full h-full"
              aria-label={tab.label}
              aria-current={isActive ? 'page' : undefined}
              role="tab"
              aria-selected={isActive}
            >
              <tab.icon
                size={24}
                className={`mb-1 transition-colors ${
                  isActive ? 'text-pink-500' : 'text-slate-400'
                }`}
                aria-hidden="true"
              />
              <span
                className={`text-[10px] font-medium ${
                  isActive ? 'text-pink-500' : 'text-slate-500'
                }`}
              >
                {tab.label}
              </span>
            </button>
          );
        })}
      </nav>
    </div>
  );
};
