// cloudflow-frontend-vue/src/components/common/AnnouncementBell.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import Icon from '@/components/icons/Icon.vue'
import { useAnnouncementStore } from '@/stores/announcement'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errorMessage'
import type { Announcement } from '@/types'

const announcementStore = useAnnouncementStore()
const toast = useToastStore()
const router = useRouter()
const isOpen = ref(false)
const dropdownRef = ref<HTMLElement | null>(null)

const unreadCount = computed(() => announcementStore.unreadCount)
const announcements = computed(() => announcementStore.announcements.slice(0, 6))

function formatTime(value?: string) {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
}

async function openDetail(item: Announcement) {
  isOpen.value = false
  if (!item.isRead) {
    try {
      await announcementStore.markAsRead(item.announcementId)
    } catch (error) {
      toast.error(getErrorMessage(error, '标记公告已读失败'))
    }
  }
  router.push('/announcement')
}

async function markAllAsRead() {
  try {
    await announcementStore.markAllAsRead()
    toast.success('所有公告已标记为已读')
  } catch (error) {
    toast.error(getErrorMessage(error, '标记公告已读失败'))
  }
}

function handleClickOutside(event: MouseEvent) {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    isOpen.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  void announcementStore.fetchAnnouncements()
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<template>
  <div ref="dropdownRef" class="relative">
    <button
      type="button"
      class="relative rounded-lg p-2 text-gray-600 transition-colors hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-dark-700"
      aria-label="公告"
      @click.stop="isOpen = !isOpen"
    >
      <Icon name="bell" size="md" />
      <span v-if="unreadCount > 0" class="absolute right-1 top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] font-semibold leading-none text-white">
        {{ unreadCount > 99 ? '99+' : unreadCount }}
      </span>
    </button>

    <transition name="dropdown">
      <div v-if="isOpen" class="absolute right-0 z-50 mt-2 w-[22rem] overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-lg dark:border-dark-700 dark:bg-dark-800">
        <div class="flex items-center justify-between border-b border-gray-100 px-4 py-3 dark:border-dark-700">
          <div>
            <p class="text-sm font-semibold text-gray-900 dark:text-white">公告</p>
            <p class="mt-0.5 text-xs text-gray-500 dark:text-dark-400">未读 {{ unreadCount }} 条</p>
          </div>
          <button v-if="unreadCount > 0" type="button" class="btn btn-ghost btn-sm" @click="markAllAsRead">全部已读</button>
        </div>

        <div class="max-h-[24rem] overflow-y-auto">
          <div v-if="announcementStore.loading" class="empty-state py-10">
            <Icon name="loader" size="lg" class="empty-state-icon animate-spin" />
            <p class="empty-state-title text-sm">正在加载公告</p>
          </div>
          <template v-else-if="announcements.length > 0">
            <button
              v-for="item in announcements"
              :key="item.announcementId"
              type="button"
              class="flex w-full items-start gap-3 border-b border-gray-100 px-4 py-3 text-left transition-colors last:border-b-0 hover:bg-gray-50 dark:border-dark-700 dark:hover:bg-dark-700/50"
              @click="openDetail(item)"
            >
              <span class="mt-1 h-2 w-2 shrink-0 rounded-full" :class="item.isRead ? 'bg-gray-300 dark:bg-dark-600' : 'bg-primary-500'" />
              <span class="min-w-0 flex-1">
                <span class="block truncate text-sm font-medium text-gray-900 dark:text-white">{{ item.title }}</span>
                <span class="mt-1 block truncate text-xs text-gray-500 dark:text-dark-400">{{ formatTime(item.publishTime || item.createTime) }}</span>
              </span>
            </button>
          </template>
          <div v-else class="empty-state py-10">
            <Icon name="inbox" size="lg" class="empty-state-icon" />
            <p class="empty-state-title text-sm">暂无公告</p>
            <p class="empty-state-description text-xs">新公告发布后会显示在这里</p>
          </div>
        </div>

        <button type="button" class="flex w-full items-center justify-center gap-2 border-t border-gray-100 px-4 py-3 text-sm font-medium text-primary-600 transition-colors hover:bg-primary-50 dark:border-dark-700 dark:hover:bg-primary-900/20" @click="isOpen = false; router.push('/announcement')">
          查看公告中心
          <Icon name="chevronRight" size="sm" />
        </button>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: scale(0.95) translateY(-4px);
}
</style>

// cloudflow-frontend-tauri/src/components/common/AnnouncementBell.tsx
import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Bell, Check, ChevronRight, Inbox, Info, X } from 'lucide-react';
import { toast } from 'sonner';
import { getErrorMessage } from '@/utils/errorMessage';
import { AnnouncementDetailModal } from '@/components/common/AnnouncementDetailModal';
import { useAnnouncementStore, useAnnouncementUnreadCount } from '@/stores/announcementStore';
import type { Announcement } from '@/types';
import { formatAnnouncementRelativeTime } from '@/utils/announcementFormat';
import { lockBodyScroll } from '@/utils/bodyScrollLock';
import './announcement-overlays.css';

export const AnnouncementBell: React.FC = () => {
  const announcements = useAnnouncementStore((state) => state.announcements);
  const loading = useAnnouncementStore((state) => state.loading);
  const fetchAnnouncements = useAnnouncementStore((state) => state.fetchAnnouncements);
  const markAsRead = useAnnouncementStore((state) => state.markAsRead);
  const markAllAsRead = useAnnouncementStore((state) => state.markAllAsRead);
  const unreadCount = useAnnouncementUnreadCount();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedAnnouncement, setSelectedAnnouncement] = useState<Announcement | null>(null);

  useEffect(() => {
    if (!isModalOpen) {
      return;
    }

    void fetchAnnouncements(true);
  }, [fetchAnnouncements, isModalOpen]);

  useEffect(() => {
    if (!isModalOpen) {
      return;
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !selectedAnnouncement) {
        setIsModalOpen(false);
      }
    };

    const unlockBodyScroll = lockBodyScroll();
    window.addEventListener('keydown', handleEscape);

    return () => {
      unlockBodyScroll();
      window.removeEventListener('keydown', handleEscape);
    };
  }, [isModalOpen, selectedAnnouncement]);

  function openModal() {
    setIsModalOpen(true);
  }

  function closeModal() {
    setIsModalOpen(false);
  }

  async function openDetail(announcement: Announcement) {
    const nextAnnouncement = announcement.isRead ? announcement : { ...announcement, isRead: true };
    setSelectedAnnouncement(nextAnnouncement);

    if (!announcement.isRead) {
      await markAsRead(announcement.announcementId);
    }
  }

  function closeDetail() {
    setSelectedAnnouncement(null);
  }

  async function markAsReadAndClose(announcementId: number) {
    await markAsRead(announcementId);
    closeDetail();
  }

  async function handleMarkAllAsRead() {
    try {
      await markAllAsRead();
      toast.success('所有公告已标记为已读');
      setSelectedAnnouncement((previous) => (previous ? { ...previous, isRead: true } : previous));
    } catch (error) {
      toast.error(getErrorMessage(error, '标记公告已读失败'));
    }
  }

  return (
    <div>
      <button
        type="button"
        onClick={openModal}
        className={`relative flex h-9 w-9 items-center justify-center rounded-lg text-gray-600 transition-all hover:scale-105 hover:bg-gray-100 dark:text-slate-400 dark:hover:bg-slate-800 ${
          unreadCount > 0 ? 'text-blue-600 dark:text-blue-400' : ''
        }`}
        aria-label="公告"
      >
        <Bell size={18} />
        {unreadCount > 0 ? (
          <span className="absolute right-1 top-1 flex h-2 w-2">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-500 opacity-75" />
            <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />
          </span>
        ) : null}
      </button>

      {isModalOpen && typeof document !== 'undefined'
        ? createPortal(
          <div
            className="cf-announcement-layer fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-gradient-to-br from-black/70 via-black/60 to-black/70 p-4 pt-[8vh] backdrop-blur-md"
            onClick={closeModal}
          >
            <div
              className="cf-announcement-panel w-full max-w-[620px] overflow-hidden rounded-3xl bg-white shadow-2xl ring-1 ring-black/5 dark:bg-slate-950 dark:ring-slate-700/70"
              onClick={(event) => event.stopPropagation()}
            >
              <div className="relative overflow-hidden border-b border-gray-100/80 bg-gradient-to-br from-blue-50/50 to-indigo-50/30 px-6 py-5 dark:border-slate-800 dark:from-blue-950/25 dark:to-slate-950">
                <div className="relative z-10 flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 text-white shadow-lg shadow-blue-500/30">
                        <Bell size={16} />
                      </div>
                      <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                        公告
                      </h2>
                    </div>
                    {unreadCount > 0 ? (
                      <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                        <span className="font-medium text-blue-600 dark:text-blue-400">{unreadCount}</span>
                        <span className="ml-1">未读</span>
                      </p>
                    ) : null}
                  </div>

                  <div className="flex items-center gap-2">
                    {unreadCount > 0 ? (
                      <button
                        type="button"
                        onClick={() => void handleMarkAllAsRead()}
                        disabled={loading}
                        className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-medium text-white shadow-lg shadow-blue-500/30 transition-all hover:bg-blue-700 hover:shadow-xl disabled:opacity-50 dark:bg-blue-500 dark:hover:bg-blue-600"
                      >
                        全部已读
                      </button>
                    ) : null}
                    <button
                      type="button"
                      onClick={closeModal}
                      className="flex h-9 w-9 items-center justify-center rounded-lg bg-white/50 text-gray-500 backdrop-blur-sm transition-all hover:bg-white hover:text-gray-700 dark:bg-slate-900/70 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-200"
                      aria-label="关闭"
                    >
                      <X size={16} />
                    </button>
                  </div>
                </div>

                <div className="absolute right-0 top-0 h-full w-48 bg-gradient-to-l from-indigo-100/20 to-transparent dark:from-indigo-900/10" />
              </div>

              <div className="cf-announcement-scroll max-h-[65vh] overflow-y-auto">
                {loading ? (
                  <div className="flex items-center justify-center py-16">
                    <div className="relative">
                      <div className="h-12 w-12 animate-spin rounded-full border-4 border-gray-200 border-t-blue-600 dark:border-slate-700 dark:border-t-blue-400" />
                      <div className="absolute inset-0 h-12 w-12 animate-pulse rounded-full border-4 border-blue-400/30" />
                    </div>
                  </div>
                ) : announcements.length > 0 ? (
                  <div>
                    {announcements.map((item) => (
                      <div
                        key={item.announcementId}
                        className={`group relative flex min-h-[72px] items-center gap-4 border-b border-gray-100 px-6 py-4 transition-all hover:bg-gray-50 dark:border-slate-800 dark:hover:bg-slate-900/70 ${
                          !item.isRead ? 'bg-blue-50/30 dark:bg-blue-900/5' : ''
                        }`}
                        onClick={() => void openDetail(item)}
                      >
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center">
                          {!item.isRead ? (
                            <div className="relative flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 text-white shadow-lg shadow-blue-500/30">
                              <span className="absolute inline-flex h-full w-full animate-ping rounded-xl bg-blue-400 opacity-75" />
                              <Info className="relative z-10 h-5 w-5" strokeWidth={2.5} />
                            </div>
                          ) : (
                            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-100 text-gray-400 dark:bg-slate-900 dark:text-slate-500">
                              <Check className="h-5 w-5" />
                            </div>
                          )}
                        </div>

                        <div className="flex min-w-0 flex-1 items-center justify-between gap-4">
                          <div className="min-w-0 flex-1">
                            <h3 className="truncate text-sm font-medium text-gray-900 dark:text-white">
                              {item.title}
                            </h3>
                            <div className="mt-1 flex items-center gap-2">
                              <time className="text-xs text-gray-500 dark:text-gray-400">
                                {formatAnnouncementRelativeTime(item.publishTime || item.createTime)}
                              </time>
                              {!item.isRead ? (
                                <span className="inline-flex items-center gap-1 rounded-md bg-blue-100 px-1.5 py-0.5 text-xs font-medium text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
                                  <span className="relative flex h-1.5 w-1.5">
                                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-blue-500 opacity-75" />
                                    <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-blue-600" />
                                  </span>
                                  未读
                                </span>
                              ) : null}
                            </div>
                          </div>

                          <div className="flex-shrink-0">
                            <ChevronRight className="h-5 w-5 text-gray-400 transition-transform group-hover:translate-x-1 dark:text-gray-600" />
                          </div>
                        </div>

                        {!item.isRead ? (
                          <div className="absolute left-0 top-0 h-full w-1 bg-gradient-to-b from-blue-500 to-indigo-600" />
                        ) : null}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-16">
                    <div className="relative mb-4">
                      <div className="flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-gray-100 to-gray-200 dark:from-slate-800 dark:to-slate-900">
                        <Inbox size={28} className="text-gray-400 dark:text-gray-500" />
                      </div>
                      <div className="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-green-500 text-white">
                        <Check className="h-3.5 w-3.5" />
                      </div>
                    </div>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">暂无公告</p>
                    <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">暂时没有任何系统公告</p>
                  </div>
                )}
              </div>
            </div>
          </div>,
          document.body,
        )
        : null}

      <AnnouncementDetailModal
        announcement={selectedAnnouncement}
        onClose={closeDetail}
        onMarkAsRead={markAsReadAndClose}
        zIndexClassName="z-[110]"
      />
    </div>
  );
};
