// cloudflow-frontend/src/components/common/EmptyState.tsx
import React from 'react';
import { Inbox } from 'lucide-react';
import { Button } from '@/components/ui';
import { cn } from '@/utils/cn';

interface EmptyStateProps {
  icon?: React.ReactNode;
  title?: string;
  description?: string;
  actionText?: string;
  onAction?: () => void;
  className?: string;
}

export const EmptyState: React.FC<EmptyStateProps> = ({
  icon,
  title = '暂无数据',
  description = '',
  actionText,
  onAction,
  className,
}) => (
  <div className={cn('empty-state', className)}>
    <div className="mb-5 flex h-20 w-20 items-center justify-center rounded-2xl bg-slate-100 dark:bg-slate-900">
      {icon || <Inbox className="empty-state-icon h-10 w-10" />}
    </div>
    <h3 className="empty-state-title">{title}</h3>
    {description ? <p className="empty-state-description">{description}</p> : null}
    {actionText && onAction ? (
      <div className="mt-6">
        <Button onClick={onAction}>{actionText}</Button>
      </div>
    ) : null}
  </div>
);

// cloudflow-frontend-vue/src/components/common/EmptyState.vue
<script setup lang="ts">
import Icon from '@/components/icons/Icon.vue'

withDefaults(defineProps<{
  title?: string
  description?: string
  icon?: string
}>(), {
  title: '暂无数据',
  description: '',
  icon: 'inbox'
})
</script>

<template>
  <div class="empty-state rounded-xl border border-dashed border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-800/50">
    <Icon :name="icon" size="xl" class="empty-state-icon" />
    <p class="empty-state-title">{{ title }}</p>
    <p v-if="description" class="empty-state-description">{{ description }}</p>
    <div v-if="$slots.default" class="mt-5">
      <slot />
    </div>
  </div>
</template>
