// cloudflow-frontend/src/components/common/SearchInput.tsx
import React, { useEffect } from 'react';
import { Search } from 'lucide-react';
import { Input } from '@/components/ui';
import { cn } from '@/utils/cn';

interface SearchInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> {
  value: string;
  placeholder?: string;
  debounceMs?: number;
  onChange: (value: string) => void;
  onSearch?: (value: string) => void;
  className?: string;
  inputClassName?: string;
}

export const SearchInput: React.FC<SearchInputProps> = ({
  value,
  placeholder = '搜索',
  debounceMs = 300,
  onChange,
  onSearch,
  className,
  inputClassName,
  ...props
}) => {
  useEffect(() => {
    if (!onSearch) {
      return;
    }

    const timer = window.setTimeout(() => {
      onSearch(value);
    }, debounceMs);

    return () => {
      window.clearTimeout(timer);
    };
  }, [debounceMs, onSearch, value]);

  return (
    <div className={cn('relative w-full', className)}>
      <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
        <Search size={16} className="text-slate-400" />
      </div>
      <Input
        value={value}
        type="text"
        className={cn('pl-10', inputClassName)}
        placeholder={placeholder}
        onChange={(event) => onChange(event.target.value)}
        {...props}
      />
    </div>
  );
};

// cloudflow-frontend-vue/src/components/common/SearchInput.vue
<script setup lang="ts">
import Icon from '@/components/icons/Icon.vue'

withDefaults(defineProps<{
  modelValue?: string
  placeholder?: string
}>(), {
  placeholder: '搜索'
})

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()
</script>

<template>
  <div class="relative">
    <Icon name="search" size="sm" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
    <input
      :value="modelValue"
      :placeholder="placeholder"
      class="input pl-9"
      @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
  </div>
</template>
