// cloudflow-frontend/src/components/common/select.tsx
import React, { useState, useEffect, useLayoutEffect, useCallback, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Check, ChevronDown, Search } from 'lucide-react';
import { cn } from '@/utils/cn';

const SELECT_ITEM_DISPLAY_NAME = 'CloudFlowSelectItem';

const isSelectItemType = (type: unknown) => {
  if (!type) {
    return false;
  }

  if (type === SelectItem) {
    return true;
  }

  const candidate = type as {
    __CF_SELECT_ITEM__?: boolean;
    displayName?: string;
    type?: {
      __CF_SELECT_ITEM__?: boolean;
      displayName?: string;
    };
  };

  if (candidate.__CF_SELECT_ITEM__ || candidate.displayName === SELECT_ITEM_DISPLAY_NAME) {
    return true;
  }

  return Boolean(
    candidate.type &&
    (candidate.type.__CF_SELECT_ITEM__ || candidate.type.displayName === SELECT_ITEM_DISPLAY_NAME),
  );
};

const collectSelectLabels = (
  node: React.ReactNode,
  next: Record<string, React.ReactNode> = {},
): Record<string, React.ReactNode> => {
  React.Children.forEach(node, (child) => {
    if (!React.isValidElement<{ children?: React.ReactNode; label?: React.ReactNode; value?: string }>(child)) {
      return;
    }

    if (
      isSelectItemType(child.type) &&
      typeof child.props.value === 'string' &&
      !Object.prototype.hasOwnProperty.call(next, child.props.value)
    ) {
      next[child.props.value] = child.props.label ?? child.props.children;
    }

    if (child.props.children) {
      collectSelectLabels(child.props.children, next);
    }
  });

  return next;
};

const getTextContent = (node: React.ReactNode): string => {
  if (node === null || node === undefined || typeof node === 'boolean') {
    return '';
  }

  if (typeof node === 'string' || typeof node === 'number') {
    return String(node);
  }

  if (Array.isArray(node)) {
    return node.map(getTextContent).join(' ');
  }

  if (React.isValidElement<{ children?: React.ReactNode; label?: React.ReactNode }>(node)) {
    return getTextContent(node.props.label ?? node.props.children);
  }

  return '';
};

const countSelectItems = (node: React.ReactNode): number => {
  let count = 0;

  React.Children.forEach(node, (child) => {
    if (!React.isValidElement<{ children?: React.ReactNode }>(child)) {
      return;
    }

    if (isSelectItemType(child.type)) {
      count += 1;
      return;
    }

    if (child.props.children) {
      count += countSelectItems(child.props.children);
    }
  });

  return count;
};

const filterSelectChildren = (
  node: React.ReactNode,
  normalizedQuery: string,
): { children: React.ReactNode; count: number } => {
  let count = 0;

  const children = React.Children.map(node, (child) => {
    if (!React.isValidElement<{ children?: React.ReactNode; label?: React.ReactNode }>(child)) {
      return child;
    }

    if (isSelectItemType(child.type)) {
      const text = getTextContent(child.props.label ?? child.props.children).toLowerCase();
      const matched = !normalizedQuery || text.includes(normalizedQuery);
      if (matched) {
        count += 1;
        return child;
      }
      return null;
    }

    if (!child.props.children) {
      return child;
    }

    const filtered = filterSelectChildren(child.props.children, normalizedQuery);
    count += filtered.count;

    if (normalizedQuery && filtered.count === 0) {
      return null;
    }

    return React.cloneElement(child, undefined, filtered.children);
  });

  return { children, count };
};

const SelectContext = React.createContext<{
  value?: string;
  onValueChange?: (value: string) => void;
  disabled: boolean;
  open: boolean;
  setOpen: (open: boolean) => void;
  labels: Record<string, React.ReactNode>;
  registerLabel: (value: string, label: React.ReactNode) => void;
  searchable: boolean;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  searchPlaceholder: string;
  emptyText: string;
  containerRef: React.RefObject<HTMLDivElement | null>;
  dropdownRef: React.RefObject<HTMLDivElement | null>;
}>({
  disabled: false,
  open: false,
  setOpen: () => {},
  labels: {},
  registerLabel: () => {},
  searchable: false,
  searchQuery: '',
  setSearchQuery: () => {},
  searchPlaceholder: '搜索...',
  emptyText: '没有匹配的选项',
  containerRef: { current: null },
  dropdownRef: { current: null },
});

export const Select = ({
  children,
  value,
  onValueChange,
  disabled = false,
  searchable = 'auto',
  searchPlaceholder = '搜索...',
  emptyText = '没有匹配的选项',
}: {
  children: React.ReactNode;
  value?: string;
  onValueChange?: (value: string) => void;
  disabled?: boolean;
  searchable?: boolean | 'auto';
  searchPlaceholder?: string;
  emptyText?: string;
}) => {
  const [open, setOpen] = useState(false);
  const [labels, setLabels] = useState<Record<string, React.ReactNode>>({});
  const [searchQuery, setSearchQuery] = useState('');
  const containerRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const staticLabels = React.useMemo(() => collectSelectLabels(children), [children]);
  const optionCount = React.useMemo(() => countSelectItems(children), [children]);
  const mergedLabels = React.useMemo(
    () => ({ ...staticLabels, ...labels }),
    [staticLabels, labels],
  );
  const searchEnabled = searchable === 'auto' ? optionCount > 5 : searchable;

  const registerLabel = useCallback((val: string, label: React.ReactNode) => {
    setLabels((prev) => {
      if (prev[val] === label) return prev;
      return { ...prev, [val]: label };
    });
  }, []);

  useEffect(() => {
    if (!open) return;

    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Node;
      if (containerRef.current?.contains(target)) return;
      if (dropdownRef.current?.contains(target)) return;
      setOpen(false);
    };

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside, true);
    window.addEventListener('keydown', handleEscape);

    return () => {
      document.removeEventListener('mousedown', handleClickOutside, true);
      window.removeEventListener('keydown', handleEscape);
    };
  }, [open]);

  useEffect(() => {
    if (!open) {
      setSearchQuery('');
    }
  }, [open]);

  useEffect(() => {
    if (disabled && open) {
      setOpen(false);
    }
  }, [disabled, open]);

  return (
    <SelectContext.Provider
      value={{
        value,
        onValueChange,
        disabled,
        open,
        setOpen,
        labels: mergedLabels,
        registerLabel,
        searchable: searchEnabled,
        searchQuery,
        setSearchQuery,
        searchPlaceholder,
        emptyText,
        containerRef,
        dropdownRef,
      }}
    >
      <div className={cn('relative', open ? 'z-[120]' : 'z-0')} ref={containerRef}>
        {children}
      </div>
    </SelectContext.Provider>
  );
};

export const SelectTrigger = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => {
  const { setOpen, open, disabled } = React.useContext(SelectContext);
  const hasExplicitWidth = className
    .split(/\s+/)
    .some((token) => token.split(':').pop()?.startsWith('w-'));

  return (
    <button
      type="button"
      disabled={disabled}
      aria-expanded={open}
      aria-haspopup="listbox"
      className={cn(
        'select-trigger cf-control flex h-9 min-h-9 items-center justify-between rounded-md px-3 py-1.5 text-left text-[13px]',
        !hasExplicitWidth && 'w-full',
        open && 'select-trigger-open cf-control-active',
        disabled && 'select-trigger-disabled',
        className,
      )}
      onClick={() => {
        if (disabled) return;
        setOpen(!open);
      }}
      onKeyDown={(event) => {
        if (disabled) return;
        if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          setOpen(true);
        }
      }}
    >
      {children}
      <span className="select-icon ml-2 shrink-0">
        <ChevronDown
          size={16}
          className={cn(
            'transition-transform duration-200',
            open && 'rotate-180 text-[color:var(--cf-primary-600)] dark:text-[color:rgb(204_251_241)]',
          )}
        />
      </span>
    </button>
  );
};

export const SelectValue = ({ placeholder }: { placeholder?: string }) => {
  const { value, labels } = React.useContext(SelectContext);
  const hasRegisteredEmptyValue = Object.prototype.hasOwnProperty.call(labels, '');
  const hasValue = value !== undefined && (value !== '' || hasRegisteredEmptyValue);
  const displayValue = hasValue ? (labels[value as string] ?? value) : placeholder;

  return (
    <span
      className={cn(
        'select-value min-w-0 flex-1 truncate',
        hasValue ? 'text-slate-900 dark:text-slate-100' : 'text-slate-400 dark:text-slate-500',
      )}
    >
      {displayValue}
    </span>
  );
};

export const SelectContent = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => {
  const {
    open,
    searchable,
    searchQuery,
    setSearchQuery,
    searchPlaceholder,
    emptyText,
    setOpen,
    containerRef,
    dropdownRef,
  } = React.useContext(SelectContext);
  const [placement, setPlacement] = useState({
    top: 0,
    left: 0,
    width: 192,
    maxHeight: 256,
  });
  const [positionReady, setPositionReady] = useState(false);
  const measurementPassRef = useRef(0);
  const searchInputRef = useRef<HTMLInputElement>(null);

  const explicitWidth = className
    .split(/\s+/)
    .some((token) => {
      const base = token.split(':').pop() || '';
      return base.startsWith('w-') || base.startsWith('min-w-') || base.startsWith('max-w-');
    });

  const updatePlacement = useCallback(() => {
    if (!containerRef.current) {
      setPositionReady(false);
      return;
    }

    const rect = containerRef.current.getBoundingClientRect();
    const viewportPadding = 12;
    const defaultWidth = Math.max(rect.width, 192);
    const measuredDropdownHeight = dropdownRef.current?.offsetHeight ?? 0;
    const hasMeasuredDropdown = measuredDropdownHeight > 0;
    const dropdownWidth = explicitWidth
      ? (dropdownRef.current?.offsetWidth ?? defaultWidth)
      : defaultWidth;
    const dropdownHeight = hasMeasuredDropdown ? measuredDropdownHeight : 260;
    const spaceBelow = window.innerHeight - rect.bottom - viewportPadding;
    const spaceAbove = rect.top - viewportPadding;
    const dropUp = spaceBelow < Math.min(dropdownHeight, 256) && spaceAbove > spaceBelow;
    const maxHeight = Math.min(320, Math.max(120, (dropUp ? spaceAbove : spaceBelow) - 6));
    const renderedHeight = Math.min(dropdownHeight, maxHeight);

    let left = rect.left;
    if (left + dropdownWidth > window.innerWidth - viewportPadding) {
      left = Math.max(viewportPadding, window.innerWidth - dropdownWidth - viewportPadding);
    }

    const top = dropUp
      ? Math.max(viewportPadding, rect.top - renderedHeight - 6)
      : rect.bottom + 6;

    setPlacement({
      top,
      left,
      width: defaultWidth,
      maxHeight,
    });
    measurementPassRef.current += 1;
    setPositionReady(hasMeasuredDropdown && measurementPassRef.current >= 2);
  }, [containerRef, dropdownRef, explicitWidth]);

  useLayoutEffect(() => {
    if (!open) {
      measurementPassRef.current = 0;
      setPositionReady(false);
      return;
    }

    measurementPassRef.current = 0;
    setPositionReady(false);
    updatePlacement();
    let rafId = window.requestAnimationFrame(() => {
      updatePlacement();
      rafId = window.requestAnimationFrame(updatePlacement);
    });
    window.addEventListener('resize', updatePlacement);
    window.addEventListener('scroll', updatePlacement, true);

    return () => {
      measurementPassRef.current = 0;
      window.cancelAnimationFrame(rafId);
      window.removeEventListener('resize', updatePlacement);
      window.removeEventListener('scroll', updatePlacement, true);
    };
  }, [open, updatePlacement]);

  useEffect(() => {
    if (open && searchable && positionReady) {
      searchInputRef.current?.focus();
    }
  }, [open, positionReady, searchable]);

  if (!open || typeof document === 'undefined') {
    return null;
  }

  const normalizedQuery = searchQuery.trim().toLowerCase();
  const filtered = filterSelectChildren(children, normalizedQuery);

  return createPortal(
    <div
      ref={dropdownRef}
      role="listbox"
      className={cn(
        'select-dropdown-portal fixed z-[160] overflow-hidden rounded-md border border-slate-200 bg-[var(--cf-surface-strong)] text-slate-900 shadow-none dark:border-slate-800 dark:bg-slate-950 dark:text-slate-100 dark:shadow-none',
        className,
      )}
      style={{
        top: placement.top,
        left: placement.left,
        width: explicitWidth ? undefined : placement.width,
        maxHeight: placement.maxHeight,
        visibility: positionReady ? 'visible' : 'hidden',
        pointerEvents: positionReady ? undefined : 'none',
      }}
    >
      {searchable ? (
        <div className="select-search">
          <Search size={16} className="shrink-0 text-slate-400" />
          <input
            ref={searchInputRef}
            className="select-search-input cf-control"
            value={searchQuery}
            type="text"
            placeholder={searchPlaceholder}
            onChange={(event) => setSearchQuery(event.target.value)}
            onClick={(event) => event.stopPropagation()}
            onKeyDown={(event) => {
              if (event.key === 'Escape') {
                event.preventDefault();
                setOpen(false);
              }
            }}
          />
        </div>
      ) : null}
      <div className="select-options">
        {filtered.count > 0 ? filtered.children : <div className="select-empty">{emptyText}</div>}
      </div>
    </div>,
    document.body,
  );
};

type SelectItemProps = {
  children: React.ReactNode;
  value: string;
  label?: React.ReactNode;
  className?: string;
  disabled?: boolean;
};

type SelectItemComponent = React.FC<SelectItemProps> & {
  __CF_SELECT_ITEM__?: boolean;
};

export const SelectItem: SelectItemComponent = ({ children, value, label, className = '', disabled = false }) => {
  const { value: selectedValue, onValueChange, setOpen, registerLabel } = React.useContext(SelectContext);
  const isSelected = selectedValue === value;

  useEffect(() => {
    registerLabel(value, label ?? children);
  }, [value, children, label, registerLabel]);

  return (
    <div
      role="option"
      aria-selected={isSelected}
      className={cn(
        'select-option relative flex w-full cursor-pointer items-center justify-between gap-2 px-3 py-2 text-[13px] transition-colors',
        disabled && 'select-option-disabled cursor-not-allowed opacity-40',
        isSelected
          ? 'select-option-selected cf-option-active'
          : 'text-slate-700 hover:bg-[var(--cf-surface-muted)] hover:text-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 dark:hover:text-white',
        className,
      )}
      onClick={() => {
        if (disabled) return;
        onValueChange?.(value);
        setOpen(false);
      }}
    >
      <div className="select-option-label min-w-0 flex-1 overflow-hidden text-left">{children}</div>
      {isSelected ? (
        <Check size={16} className="select-check shrink-0 text-[color:var(--cf-primary-600)] dark:text-[color:rgb(204_251_241)]" />
      ) : null}
    </div>
  );
};

SelectItem.displayName = SELECT_ITEM_DISPLAY_NAME;
SelectItem.__CF_SELECT_ITEM__ = true;

// cloudflow-frontend-vue/src/components/common/Select.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import Icon from '@/components/icons/Icon.vue'
import type { SelectOption } from './types'

const props = withDefaults(defineProps<{
  modelValue?: string | number | boolean | null
  options: SelectOption[] | Array<Record<string, unknown>>
  placeholder?: string
  disabled?: boolean
  error?: boolean
  searchable?: boolean
  searchPlaceholder?: string
  emptyText?: string
  valueKey?: string
  labelKey?: string
  triggerClass?: string
}>(), {
  disabled: false,
  error: false,
  searchable: false,
  valueKey: 'value',
  labelKey: 'label',
  placeholder: '请选择',
  searchPlaceholder: '搜索',
  emptyText: '无可选项',
  triggerClass: ''
})

const emit = defineEmits<{
  'update:modelValue': [value: string | number | boolean | null]
  change: [value: string | number | boolean | null, option: SelectOption | null]
}>()

const isOpen = ref(false)
const searchQuery = ref('')
const focusedIndex = ref(-1)
const containerRef = ref<HTMLElement | null>(null)
const triggerRef = ref<HTMLButtonElement | null>(null)
const searchInputRef = ref<HTMLInputElement | null>(null)
const dropdownRef = ref<HTMLElement | null>(null)
const optionsListRef = ref<HTMLElement | null>(null)
const triggerRect = ref<DOMRect | null>(null)
const dropdownPosition = ref<'bottom' | 'top'>('bottom')
const instanceId = `select-${Math.random().toString(36).slice(2, 9)}`

const getRecord = (option: unknown) => typeof option === 'object' && option !== null ? option as Record<string, unknown> : null
const getOptionValue = (option: unknown) => getRecord(option)?.[props.valueKey] ?? option
const getOptionLabel = (option: unknown) => {
  const record = getRecord(option)
  return record ? String(record[props.labelKey] ?? '') : String(option ?? '')
}
const getOptionDescription = (option: unknown) => {
  const record = getRecord(option)
  return record?.description == null ? '' : String(record.description)
}
const isOptionDisabled = (option: unknown) => Boolean(getRecord(option)?.disabled)
const isGroupHeaderOption = (option: unknown) => getRecord(option)?.kind === 'group'
const isSelected = (option: unknown) => getOptionValue(option) === props.modelValue

const selectedOption = computed(() => props.options.find((opt) => isSelected(opt)) || null)
const selectedLabel = computed(() => selectedOption.value ? getOptionLabel(selectedOption.value) : props.placeholder)
const filteredOptions = computed(() => {
  const query = searchQuery.value.trim().toLowerCase()
  if (!props.searchable || !query) return props.options
  return props.options.filter((opt) => {
    const label = getOptionLabel(opt).toLowerCase()
    const description = getOptionDescription(opt).toLowerCase()
    return label.includes(query) || description.includes(query)
  })
})

const updateTriggerRect = () => {
  if (containerRef.value) triggerRect.value = containerRef.value.getBoundingClientRect()
}

const dropdownStyle = computed(() => {
  if (!triggerRect.value) return {}
  const rect = triggerRect.value
  const style: Record<string, string> = {
    position: 'fixed',
    left: `${rect.left}px`,
    minWidth: `${rect.width}px`,
    zIndex: '100000020'
  }
  if (dropdownPosition.value === 'top') {
    style.bottom = `${window.innerHeight - rect.top + 4}px`
  } else {
    style.top = `${rect.bottom + 4}px`
  }
  return style
})

const calculateDropdownPosition = () => {
  updateTriggerRect()
  nextTick(() => {
    if (!dropdownRef.value || !triggerRect.value) return
    const dropdownHeight = dropdownRef.value.offsetHeight || 240
    const spaceBelow = window.innerHeight - triggerRect.value.bottom
    const spaceAbove = triggerRect.value.top
    dropdownPosition.value = spaceBelow < dropdownHeight && spaceAbove > dropdownHeight ? 'top' : 'bottom'
  })
}

const findNextEnabledIndex = (startIndex: number) => {
  const opts = filteredOptions.value
  if (opts.length === 0) return -1
  for (let offset = 0; offset < opts.length; offset += 1) {
    const index = (startIndex + offset) % opts.length
    if (!isOptionDisabled(opts[index]) && !isGroupHeaderOption(opts[index])) return index
  }
  return -1
}

const findPrevEnabledIndex = (startIndex: number) => {
  const opts = filteredOptions.value
  if (opts.length === 0) return -1
  for (let offset = 0; offset < opts.length; offset += 1) {
    const index = (startIndex - offset + opts.length) % opts.length
    if (!isOptionDisabled(opts[index]) && !isGroupHeaderOption(opts[index])) return index
  }
  return -1
}

const scrollToFocused = () => {
  nextTick(() => {
    const list = optionsListRef.value
    if (!list || focusedIndex.value < 0) return
    const focusedEl = list.children[focusedIndex.value] as HTMLElement | undefined
    if (!focusedEl) return
    if (focusedEl.offsetTop < list.scrollTop) {
      list.scrollTop = focusedEl.offsetTop
    } else if (focusedEl.offsetTop + focusedEl.offsetHeight > list.scrollTop + list.offsetHeight) {
      list.scrollTop = focusedEl.offsetTop + focusedEl.offsetHeight - list.offsetHeight
    }
  })
}

const selectOption = (option: unknown) => {
  if (isOptionDisabled(option) || isGroupHeaderOption(option)) return
  const value = (getOptionValue(option) ?? null) as string | number | boolean | null
  emit('update:modelValue', value)
  emit('change', value, getRecord(option) as SelectOption | null)
  isOpen.value = false
  triggerRef.value?.focus()
}

const toggle = () => {
  if (!props.disabled) isOpen.value = !isOpen.value
}

const onTriggerKeyDown = () => {
  if (!isOpen.value) isOpen.value = true
}

const onDropdownKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'ArrowDown') {
    event.preventDefault()
    focusedIndex.value = findNextEnabledIndex(focusedIndex.value + 1)
    scrollToFocused()
  } else if (event.key === 'ArrowUp') {
    event.preventDefault()
    focusedIndex.value = findPrevEnabledIndex(focusedIndex.value - 1)
    scrollToFocused()
  } else if (event.key === 'Enter') {
    event.preventDefault()
    const option = filteredOptions.value[focusedIndex.value]
    if (option) selectOption(option)
  } else if (event.key === 'Escape') {
    event.preventDefault()
    isOpen.value = false
    triggerRef.value?.focus()
  } else if (event.key === 'Tab') {
    isOpen.value = false
  }
}

const handleClickOutside = (event: MouseEvent) => {
  const target = event.target as HTMLElement
  const isInDropdown = Boolean(target.closest(`.${instanceId}`))
  const isInTrigger = containerRef.value?.contains(target)
  if (!isInDropdown && !isInTrigger) isOpen.value = false
}

watch(isOpen, (open) => {
  if (open) {
    calculateDropdownPosition()
    const selectedIndex = filteredOptions.value.findIndex((opt) => isSelected(opt))
    focusedIndex.value = selectedIndex >= 0 ? selectedIndex : findNextEnabledIndex(0)
    if (props.searchable) void nextTick(() => searchInputRef.value?.focus())
    window.addEventListener('scroll', updateTriggerRect, { capture: true, passive: true })
    window.addEventListener('resize', calculateDropdownPosition)
  } else {
    searchQuery.value = ''
    focusedIndex.value = -1
    window.removeEventListener('scroll', updateTriggerRect, { capture: true })
    window.removeEventListener('resize', calculateDropdownPosition)
  }
})

onMounted(() => document.addEventListener('click', handleClickOutside))
onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  window.removeEventListener('scroll', updateTriggerRect, { capture: true })
  window.removeEventListener('resize', calculateDropdownPosition)
})
</script>

<template>
  <div ref="containerRef" class="relative">
    <button
      ref="triggerRef"
      type="button"
      class="select-trigger"
      :class="[isOpen && 'select-trigger-open', error && 'select-trigger-error', disabled && 'select-trigger-disabled', triggerClass]"
      :disabled="disabled"
      :aria-expanded="isOpen"
      aria-haspopup="listbox"
      aria-label="选择选项"
      @click="toggle"
      @keydown.down.prevent="onTriggerKeyDown"
      @keydown.up.prevent="onTriggerKeyDown"
    >
      <span v-if="$slots.prefix" class="select-prefix">
        <slot name="prefix" />
      </span>
      <span class="select-value">
        <slot name="selected" :option="selectedOption">{{ selectedLabel }}</slot>
      </span>
      <span class="select-icon">
        <Icon name="chevronDown" size="md" class="transition-transform duration-200" :class="isOpen ? 'rotate-180' : ''" />
      </span>
    </button>

    <Teleport to="body">
      <Transition name="select-dropdown">
        <div
          v-if="isOpen"
          ref="dropdownRef"
          class="select-dropdown-portal"
          :class="instanceId"
          :style="dropdownStyle"
          role="listbox"
          @click.stop
          @mousedown.stop
          @keydown="onDropdownKeyDown"
        >
          <div v-if="searchable" class="select-search">
            <Icon name="search" size="sm" class="text-slate-400" />
            <input ref="searchInputRef" v-model="searchQuery" type="text" :placeholder="searchPlaceholder" class="select-search-input" @click.stop />
          </div>
          <div ref="optionsListRef" class="select-options">
            <button
              v-for="(option, index) in filteredOptions"
              :key="`${typeof getOptionValue(option)}:${String(getOptionValue(option) ?? '')}`"
              type="button"
              class="select-option"
              :class="[isGroupHeaderOption(option) && 'select-option-group', isSelected(option) && 'select-option-selected', isOptionDisabled(option) && !isGroupHeaderOption(option) && 'select-option-disabled', focusedIndex === index && !isGroupHeaderOption(option) && 'select-option-focused']"
              :disabled="isOptionDisabled(option)"
              role="option"
              :aria-selected="isSelected(option)"
              @mouseenter="!isOptionDisabled(option) && !isGroupHeaderOption(option) && (focusedIndex = index)"
              @click="selectOption(option)"
            >
              <slot name="option" :option="option" :selected="isSelected(option)">
                <span class="select-option-label">{{ getOptionLabel(option) }}</span>
                <Icon v-if="isSelected(option)" name="check" size="sm" class="text-teal-600" />
              </slot>
            </button>
            <div v-if="filteredOptions.length === 0" class="select-empty">{{ emptyText }}</div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<style scoped>
.select-trigger {
  position: relative;
  display: flex;
  min-height: 2.75rem;
  width: 100%;
  cursor: pointer;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  border-radius: 0.75rem;
  border: 1px solid rgb(226 232 240);
  background: white;
  padding: 0.5rem 0.75rem;
  text-align: left;
  color: rgb(15 23 42);
  outline: none;
  transition: border-color 0.18s ease, box-shadow 0.18s ease, background-color 0.18s ease;
}

.select-trigger.cf-auth-select-trigger {
  min-height: 2.875rem;
  border-radius: 0.9rem;
  padding-left: 2.75rem;
  padding-right: 0.95rem;
  font-size: 0.95rem;
}

.select-trigger:hover {
  border-color: rgb(203 213 225);
}

.select-trigger:focus,
.select-trigger-open {
  border-color: rgb(20 184 166);
  box-shadow: 0 0 0 3px rgb(20 184 166 / 0.14);
}

.select-trigger-error {
  border-color: rgb(239 68 68);
  box-shadow: 0 0 0 3px rgb(239 68 68 / 0.16);
}

.select-trigger-disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

.select-icon {
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  color: rgb(148 163 184);
}

.select-prefix {
  pointer-events: none;
  position: absolute;
  left: 0.75rem;
  top: 50%;
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  color: rgb(148 163 184);
  transform: translateY(-50%);
}

.select-value {
  min-width: 0;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

:global(.dark) .select-trigger {
  border-color: rgb(51 65 85);
  background: rgb(2 6 23 / 0.72);
  color: rgb(248 250 252);
}
</style>

<style>
.select-dropdown-portal {
  width: max-content;
  min-width: 200px;
  overflow: hidden;
  border-radius: 0.75rem;
  border: 1px solid rgb(226 232 240);
  background: white;
  box-shadow: 0 18px 40px rgb(15 23 42 / 0.16);
  pointer-events: auto !important;
}

.dark .select-dropdown-portal {
  border-color: rgb(51 65 85);
  background: rgb(15 23 42);
  box-shadow: 0 22px 44px rgb(2 6 23 / 0.42);
}

.select-search {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  border-bottom: 1px solid rgb(241 245 249);
  padding: 0.5rem 0.75rem;
}

.dark .select-search {
  border-bottom-color: rgb(30 41 59);
}

.select-search-input {
  min-width: 0;
  flex: 1;
  border: 0;
  background: transparent;
  font-size: 0.875rem;
  color: rgb(15 23 42);
  outline: none;
}

.dark .select-search-input {
  color: rgb(248 250 252);
}

.select-options {
  max-height: 15rem;
  overflow-y: auto;
  padding: 0.25rem 0;
}

.select-option {
  display: flex;
  width: 100%;
  cursor: pointer;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  border: 0;
  background: transparent;
  padding: 0.625rem 1rem;
  text-align: left;
  font-size: 0.875rem;
  color: rgb(51 65 85);
  transition: background-color 0.15s ease, color 0.15s ease;
}

.select-option:hover,
.select-option-focused {
  background: rgb(248 250 252);
}

.select-option-selected {
  background: rgb(240 253 250);
  color: rgb(15 118 110);
}

.select-option-disabled {
  cursor: not-allowed;
  opacity: 0.45;
}

.select-option-group {
  cursor: default;
  background: rgb(248 250 252);
  font-size: 0.6875rem;
  font-weight: 700;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: rgb(100 116 139);
}

.select-option-label {
  min-width: 0;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.select-empty {
  padding: 2rem 1rem;
  text-align: center;
  font-size: 0.875rem;
  color: rgb(100 116 139);
}

.dark .select-option {
  color: rgb(203 213 225);
}

.dark .select-option:hover,
.dark .select-option-focused {
  background: rgb(30 41 59);
}

.dark .select-option-selected {
  background: rgb(20 184 166 / 0.16);
  color: rgb(94 234 212);
}

.dark .select-option-group {
  background: rgb(15 23 42);
  color: rgb(148 163 184);
}

.select-dropdown-enter-active,
.select-dropdown-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.select-dropdown-enter-from,
.select-dropdown-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>
