// cloudflow-frontend/src/pages/hr/HrHeadcountPage.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, BriefcaseBusiness, Building2, FilePlus2, Layers3, RefreshCcw, Search, Users } from 'lucide-react';
import { toast } from 'sonner';
import {
  Button,
  Card,
  Input,
  Label,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui';
import {
  Headcount,
  HeadcountPayload,
  HeadcountStatistics,
  HeadcountTargetType,
  PostOption,
  getDeptTreeOptions,
  getHeadcountStatistics,
  getPostOptions,
  listHeadcounts,
  setHeadcount,
  updateHeadcountActualCount,
} from '@/services/api/hr';
import { flattenDeptTree, normalizeRows, toDateInputValue } from './hrShared';

const ALL_TARGETS = '__all__';
const LIST_SCOPE_ACTIVE = 'ACTIVE';
const LIST_SCOPE_ALL = 'ALL';

const createDefaultForm = (): HeadcountPayload => ({
  targetType: 'DEPT',
  targetId: 0,
  approvedCount: 1,
  effectiveDate: '',
  expiryDate: '',
});

const targetTypeLabel = (targetType?: HeadcountTargetType | string | null) =>
  targetType === 'POST' ? '岗位编制' : '部门编制';

const formatUtilizationRate = (value?: number | string | null) => {
  const numericValue = Number(value);
  if (!Number.isFinite(numericValue)) return '-';
  return `${numericValue.toFixed(numericValue % 1 === 0 ? 0 : 2)}%`;
};

const vacancyTone = (headcount: Pick<Headcount, 'approvedCount' | 'actualCount' | 'vacancyCount'>) => {
  if (headcount.actualCount > headcount.approvedCount || headcount.vacancyCount < 0) {
    return 'bg-rose-50 text-rose-700 border-rose-100';
  }
  if (headcount.vacancyCount > 0) {
    return 'bg-amber-50 text-amber-700 border-amber-100';
  }
  return 'bg-emerald-50 text-emerald-700 border-emerald-100';
};

export const HrHeadcountPage: React.FC = () => {
  const [headcounts, setHeadcounts] = useState<Headcount[]>([]);
  const [statistics, setStatistics] = useState<HeadcountStatistics | null>(null);
  const [deptOptions, setDeptOptions] = useState<Array<{ label: string; value: number }>>([]);
  const [postOptions, setPostOptions] = useState<PostOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [listLoading, setListLoading] = useState(false);
  const [detailLoading, setDetailLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [keyword, setKeyword] = useState('');
  const [targetFilter, setTargetFilter] = useState<string>(ALL_TARGETS);
  const [scopeFilter, setScopeFilter] = useState(LIST_SCOPE_ACTIVE);
  const [selectedHeadcountId, setSelectedHeadcountId] = useState('');
  const [actualCountInput, setActualCountInput] = useState('');
  const [createForm, setCreateForm] = useState<HeadcountPayload>(createDefaultForm);

  const loadOptions = async () => {
    try {
      const [deptRes, postRes] = await Promise.all([
        getDeptTreeOptions(),
        getPostOptions(),
      ]);
      setDeptOptions(flattenDeptTree(Array.isArray(deptRes) ? deptRes : []));
      setPostOptions(normalizeRows<PostOption>(postRes));
    } catch (error) {
      console.error(error);
      toast.error('编制基础选项加载失败');
    }
  };

  const loadHeadcountList = async (
    nextSelection?: number | { targetType: HeadcountTargetType; targetId: number },
  ) => {
    setListLoading(true);
    try {
      const data = await listHeadcounts({
        targetType: targetFilter === ALL_TARGETS ? undefined : (targetFilter as HeadcountTargetType),
        includeExpired: scopeFilter === LIST_SCOPE_ALL,
      });
      const rows = Array.isArray(data) ? data : [];
      setHeadcounts(rows);

      let nextSelectedId = '';

      if (typeof nextSelection === 'number') {
        nextSelectedId = rows.some(item => item.id === nextSelection) ? String(nextSelection) : '';
      } else if (nextSelection) {
        const matched = rows.find(item => item.targetType === nextSelection.targetType && item.targetId === nextSelection.targetId);
        nextSelectedId = matched ? String(matched.id) : '';
      } else if (selectedHeadcountId && rows.some(item => String(item.id) === selectedHeadcountId)) {
        nextSelectedId = selectedHeadcountId;
      } else if (rows[0]) {
        nextSelectedId = String(rows[0].id);
      }

      setSelectedHeadcountId(nextSelectedId);
      if (!nextSelectedId) {
        setStatistics(null);
        setActualCountInput('');
      }
    } catch (error) {
      console.error(error);
      toast.error('编制列表加载失败');
    } finally {
      setListLoading(false);
    }
  };

  const loadStatistics = async (targetType: HeadcountTargetType, targetId: number) => {
    setDetailLoading(true);
    try {
      const detail = await getHeadcountStatistics(targetType, targetId);
      setStatistics(detail);
      setActualCountInput(String(detail.actualCount ?? 0));
    } catch (error) {
      console.error(error);
      setStatistics(null);
      toast.error('编制统计加载失败');
    } finally {
      setDetailLoading(false);
    }
  };

  useEffect(() => {
    const bootstrap = async () => {
      setLoading(true);
      await Promise.all([loadOptions(), loadHeadcountList()]);
      setLoading(false);
    };
    void bootstrap();
  }, []);

  useEffect(() => {
    if (loading) return;
    void loadHeadcountList();
  }, [loading, scopeFilter, targetFilter]);

  const selectedHeadcount = useMemo(
    () => headcounts.find(item => String(item.id) === selectedHeadcountId) || null,
    [headcounts, selectedHeadcountId],
  );

  useEffect(() => {
    if (!selectedHeadcount) {
      setStatistics(null);
      setActualCountInput('');
      return;
    }

    void loadStatistics(selectedHeadcount.targetType, selectedHeadcount.targetId);
  }, [selectedHeadcount]);

  const currentTargetOptions = useMemo(
    () => (createForm.targetType === 'POST'
      ? postOptions.map(item => ({ label: item.postName, value: item.postId }))
      : deptOptions),
    [createForm.targetType, deptOptions, postOptions],
  );

  useEffect(() => {
    if (!currentTargetOptions.length) return;
    if (currentTargetOptions.some(item => item.value === createForm.targetId)) return;

    setCreateForm(prev => ({
      ...prev,
      targetId: currentTargetOptions[0]?.value || 0,
    }));
  }, [createForm.targetId, currentTargetOptions]);

  const filteredHeadcounts = useMemo(() => {
    const normalizedKeyword = keyword.trim().toLowerCase();
    if (!normalizedKeyword) return headcounts;

    return headcounts.filter(item =>
      [
        item.targetName,
        targetTypeLabel(item.targetType),
        item.targetId,
        item.approvedCount,
        item.actualCount,
        item.vacancyCount,
      ]
        .filter(value => value !== null && value !== undefined)
        .some(value => String(value).toLowerCase().includes(normalizedKeyword)),
    );
  }, [headcounts, keyword]);

  useEffect(() => {
    if (!filteredHeadcounts.length) {
      setSelectedHeadcountId('');
      return;
    }

    if (!selectedHeadcountId || !filteredHeadcounts.some(item => String(item.id) === selectedHeadcountId)) {
      setSelectedHeadcountId(String(filteredHeadcounts[0].id));
    }
  }, [filteredHeadcounts, selectedHeadcountId]);

  const metrics = useMemo(() => {
    const deptCount = headcounts.filter(item => item.targetType === 'DEPT').length;
    const postCount = headcounts.filter(item => item.targetType === 'POST').length;
    const vacancyTotal = headcounts.reduce((sum, item) => sum + Math.max(item.vacancyCount, 0), 0);
    const overstaffedCount = headcounts.filter(item => item.actualCount > item.approvedCount || item.vacancyCount < 0).length;

    return [
      { label: '编制记录', value: headcounts.length, hint: '当前查询范围内的有效编制', icon: <Layers3 size={18} />, tone: 'bg-slate-100 text-slate-600' },
      { label: '部门编制', value: deptCount, hint: '按部门维护的编制数', icon: <Building2 size={18} />, tone: 'bg-sky-50 text-sky-600' },
      { label: '岗位编制', value: postCount, hint: '按岗位维护的编制数', icon: <BriefcaseBusiness size={18} />, tone: 'bg-violet-50 text-violet-600' },
      { label: '空缺总量', value: vacancyTotal, hint: `${overstaffedCount} 项存在超编风险`, icon: <Users size={18} />, tone: 'bg-amber-50 text-amber-600' },
    ];
  }, [headcounts]);

  const resetCreateDialog = () => {
    setCreateForm({
      ...createDefaultForm(),
      targetType: 'DEPT',
      targetId: deptOptions[0]?.value || postOptions[0]?.postId || 0,
    });
    setCreateDialogOpen(false);
  };

  const handleOpenCreate = () => {
    setCreateForm({
      ...createDefaultForm(),
      targetType: 'DEPT',
      targetId: deptOptions[0]?.value || postOptions[0]?.postId || 0,
    });
    setCreateDialogOpen(true);
  };

  const handleCreate = async () => {
    if (!createForm.targetId) {
      toast.error('请选择编制目标');
      return;
    }
    if (createForm.approvedCount < 0) {
      toast.error('核定编制数不能小于 0');
      return;
    }
    if (createForm.expiryDate && createForm.effectiveDate && createForm.expiryDate < createForm.effectiveDate) {
      toast.error('失效日期不能早于生效日期');
      return;
    }

    setActionLoading(true);
    try {
      await setHeadcount({
        ...createForm,
        effectiveDate: createForm.effectiveDate || undefined,
        expiryDate: createForm.expiryDate || undefined,
      });
      toast.success('编制已保存');
      resetCreateDialog();
      await loadHeadcountList({
        targetType: createForm.targetType,
        targetId: createForm.targetId,
      });
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '保存编制失败');
    } finally {
      setActionLoading(false);
    }
  };

  const handleUpdateActualCount = async () => {
    if (!selectedHeadcount) return;
    if (!/^\d+$/.test(actualCountInput.trim())) {
      toast.error('实际在职人数必须是非负整数');
      return;
    }

    setActionLoading(true);
    try {
      await updateHeadcountActualCount(
        selectedHeadcount.targetType,
        selectedHeadcount.targetId,
        Number(actualCountInput),
      );
      toast.success('实际在职人数已更新');
      await loadHeadcountList(selectedHeadcount.id);
    } catch (error: any) {
      console.error(error);
      toast.error(error?.message || '更新实际在职人数失败');
    } finally {
      setActionLoading(false);
    }
  };

  const detailVacancyCount = statistics?.vacancyCount ?? selectedHeadcount?.vacancyCount ?? 0;
  const detailApprovedCount = statistics?.approvedCount ?? selectedHeadcount?.approvedCount ?? 0;
  const detailActualCount = statistics?.actualCount ?? selectedHeadcount?.actualCount ?? 0;

  return (
    <div className="space-y-6">
      <Card className="rounded-3xl border-white/80 bg-white/70 p-8 shadow-[0_12px_40px_rgba(15,23,42,0.06)] backdrop-blur-xl">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-700">
              <Layers3 size={14} />
              Headcount Control
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-slate-900">编制管理中心</h1>
            <p className="mt-2 text-sm text-slate-500">围绕部门和岗位维护核定编制、实际在职与空缺情况，直接联调 HR 编制接口。</p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button className="rounded-2xl" onClick={handleOpenCreate}>
              <FilePlus2 size={16} className="mr-2" />
              设置编制
            </Button>
            <Button variant="outline" className="rounded-2xl" onClick={() => void loadHeadcountList()}>
              <RefreshCcw size={16} className="mr-2" />
              刷新列表
            </Button>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        {metrics.map(metric => (
          <Card key={metric.label} className="rounded-3xl border-white/80 bg-white/70 p-6 backdrop-blur-xl">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-sm font-medium text-slate-500">{metric.label}</div>
                <div className="mt-3 text-3xl font-bold tracking-tight text-slate-900">{loading ? '--' : metric.value}</div>
                <div className="mt-2 text-xs text-slate-400">{metric.hint}</div>
              </div>
              <div className={`rounded-2xl p-3 ${metric.tone}`}>
                {metric.icon}
              </div>
            </div>
          </Card>
        ))}
      </div>

      <Card className="rounded-3xl border-white/80 bg-white/70 p-5 backdrop-blur-xl">
        <div className="grid grid-cols-1 gap-3 xl:grid-cols-[1.1fr_180px_180px_auto]">
          <div className="relative">
            <Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <Input
              className="pl-10"
              placeholder="搜索目标名称、目标类型、目标 ID"
              value={keyword}
              onChange={event => setKeyword(event.target.value)}
            />
          </div>
          <Select value={targetFilter} onValueChange={setTargetFilter}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value={ALL_TARGETS}>全部类型</SelectItem>
              <SelectItem value="DEPT">部门编制</SelectItem>
              <SelectItem value="POST">岗位编制</SelectItem>
            </SelectContent>
          </Select>
          <Select value={scopeFilter} onValueChange={setScopeFilter}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value={LIST_SCOPE_ACTIVE}>仅看有效编制</SelectItem>
              <SelectItem value={LIST_SCOPE_ALL}>包含已失效编制</SelectItem>
            </SelectContent>
          </Select>
          <Button
            variant="outline"
            onClick={() => {
              setKeyword('');
              setTargetFilter(ALL_TARGETS);
              setScopeFilter(LIST_SCOPE_ACTIVE);
            }}
          >
            重置
          </Button>
        </div>
      </Card>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1.15fr)_420px]">
        <Card className="rounded-3xl border-white/80 bg-white/70 p-2 backdrop-blur-xl">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>目标</TableHead>
                <TableHead>类型</TableHead>
                <TableHead>核定编制</TableHead>
                <TableHead>实际在职</TableHead>
                <TableHead>空缺 / 超编</TableHead>
                <TableHead>生效日期</TableHead>
                <TableHead>失效日期</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredHeadcounts.map(item => {
                const isActive = String(item.id) === selectedHeadcountId;
                const isOverstaffed = item.actualCount > item.approvedCount || item.vacancyCount < 0;

                return (
                  <TableRow
                    key={item.id}
                    className={isActive ? 'bg-sky-50/70' : undefined}
                  >
                    <TableCell>
                      <div className="font-semibold text-slate-900">{item.targetName || '-'}</div>
                      <div className="text-xs text-slate-400">目标 ID：{item.targetId}</div>
                    </TableCell>
                    <TableCell>{targetTypeLabel(item.targetType)}</TableCell>
                    <TableCell>{item.approvedCount}</TableCell>
                    <TableCell>{item.actualCount}</TableCell>
                    <TableCell>
                      <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${vacancyTone(item)}`}>
                        {isOverstaffed ? `超编 ${Math.abs(item.vacancyCount)}` : `空缺 ${item.vacancyCount}`}
                      </span>
                    </TableCell>
                    <TableCell>{toDateInputValue(item.effectiveDate) || '-'}</TableCell>
                    <TableCell>{toDateInputValue(item.expiryDate) || '长期有效'}</TableCell>
                    <TableCell className="text-right">
                      <Button size="sm" variant={isActive ? 'default' : 'outline'} onClick={() => setSelectedHeadcountId(String(item.id))}>
                        查看统计
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })}
              {!filteredHeadcounts.length && !listLoading && (
                <TableRow>
                  <TableCell colSpan={8} className="py-12 text-center text-slate-400">
                    当前筛选条件下没有编制记录
                  </TableCell>
                </TableRow>
              )}
              {(loading || listLoading) && (
                <TableRow>
                  <TableCell colSpan={8} className="py-12 text-center text-slate-400">
                    正在加载编制列表...
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </Card>

        <div className="space-y-6">
          <Card className="rounded-3xl border-white/80 bg-white/70 p-6 backdrop-blur-xl">
            <div className="mb-5 flex items-start justify-between gap-4">
              <div>
                <h2 className="text-lg font-semibold text-slate-900">编制统计</h2>
                <p className="mt-1 text-sm text-slate-500">按真实统计接口查看使用率、空缺和超编情况。</p>
              </div>
              {selectedHeadcount && (
                <Button variant="outline" onClick={() => void loadStatistics(selectedHeadcount.targetType, selectedHeadcount.targetId)}>
                  <RefreshCcw size={14} className="mr-2" />
                  刷新统计
                </Button>
              )}
            </div>

            {!selectedHeadcount && (
              <div className="rounded-3xl border border-dashed border-slate-200 bg-slate-50/80 px-6 py-16 text-center text-sm text-slate-500">
                从左侧选择一条编制记录查看详情和统计。
              </div>
            )}

            {selectedHeadcount && (
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4 md:col-span-2">
                  <div className="text-xs text-slate-400">目标名称</div>
                  <div className="mt-2 font-semibold text-slate-900">{statistics?.targetName || selectedHeadcount.targetName || '-'}</div>
                  <div className="mt-1 text-sm text-slate-500">
                    {targetTypeLabel(selectedHeadcount.targetType)} / 目标 ID：{selectedHeadcount.targetId}
                  </div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">核定编制</div>
                  <div className="mt-2 text-2xl font-semibold text-slate-900">{detailApprovedCount}</div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">实际在职</div>
                  <div className="mt-2 text-2xl font-semibold text-slate-900">{detailActualCount}</div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">空缺 / 超编</div>
                  <div className="mt-2">
                    <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${vacancyTone({
                      approvedCount: detailApprovedCount,
                      actualCount: detailActualCount,
                      vacancyCount: detailVacancyCount,
                    })}`}>
                      {detailActualCount > detailApprovedCount || detailVacancyCount < 0
                        ? `超编 ${Math.abs(detailVacancyCount)}`
                        : `空缺 ${detailVacancyCount}`}
                    </span>
                  </div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">使用率</div>
                  <div className="mt-2 text-2xl font-semibold text-slate-900">{formatUtilizationRate(statistics?.utilizationRate)}</div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">生效日期</div>
                  <div className="mt-2 font-semibold text-slate-900">{toDateInputValue(selectedHeadcount.effectiveDate) || '-'}</div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white/80 p-4">
                  <div className="text-xs text-slate-400">失效日期</div>
                  <div className="mt-2 font-semibold text-slate-900">{toDateInputValue(selectedHeadcount.expiryDate) || '长期有效'}</div>
                </div>
              </div>
            )}

            {detailLoading && <div className="mt-4 text-sm text-slate-400">正在加载统计数据...</div>}
          </Card>

          <Card className="rounded-3xl border-white/80 bg-white/70 p-6 backdrop-blur-xl">
            <div className="mb-4">
              <h2 className="text-lg font-semibold text-slate-900">维护实际在职人数</h2>
              <p className="mt-1 text-sm text-slate-500">更新后端 `actualCount` 后，会自动重算空缺人数。</p>
            </div>

            {!selectedHeadcount && (
              <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/80 px-4 py-10 text-center text-sm text-slate-500">
                先从左侧选择一条编制记录，再维护实际在职人数。
              </div>
            )}

            {selectedHeadcount && (
              <div className="space-y-4">
                <div>
                  <Label>实际在职人数</Label>
                  <Input
                    className="mt-2"
                    type="number"
                    min={0}
                    value={actualCountInput}
                    onChange={event => setActualCountInput(event.target.value)}
                  />
                </div>
                <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600">
                  当前目标：{statistics?.targetName || selectedHeadcount.targetName || '-'}，类型为 {targetTypeLabel(selectedHeadcount.targetType)}。
                </div>
                <Button className="w-full" disabled={actionLoading} onClick={() => void handleUpdateActualCount()}>
                  <BarChart3 size={16} className="mr-2" />
                  更新实际人数
                </Button>
              </div>
            )}
          </Card>
        </div>
      </div>

      {createDialogOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/80 bg-white p-6 shadow-2xl">
            <div className="mb-6 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-slate-900">设置编制</h2>
                <p className="mt-1 text-sm text-slate-500">若当前目标已有有效编制，后端会直接更新该记录。</p>
              </div>
              <Button variant="ghost" onClick={resetCreateDialog}>关闭</Button>
            </div>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <Label>目标类型</Label>
                <Select
                  value={createForm.targetType}
                  onValueChange={value => setCreateForm(prev => ({
                    ...prev,
                    targetType: value as HeadcountTargetType,
                    targetId: 0,
                  }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="DEPT">部门编制</SelectItem>
                    <SelectItem value="POST">岗位编制</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>编制目标</Label>
                <Select
                  value={createForm.targetId ? String(createForm.targetId) : undefined}
                  onValueChange={value => setCreateForm(prev => ({ ...prev, targetId: Number(value) }))}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="请选择目标" />
                  </SelectTrigger>
                  <SelectContent>
                    {currentTargetOptions.map(option => (
                      <SelectItem key={option.value} value={String(option.value)}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>核定编制数</Label>
                <Input
                  type="number"
                  min={0}
                  value={createForm.approvedCount}
                  onChange={event => setCreateForm(prev => ({
                    ...prev,
                    approvedCount: Number(event.target.value) || 0,
                  }))}
                />
              </div>

              <div>
                <Label>生效日期</Label>
                <Input
                  type="date"
                  value={createForm.effectiveDate || ''}
                  onChange={event => setCreateForm(prev => ({ ...prev, effectiveDate: event.target.value }))}
                />
              </div>

              <div className="md:col-span-2">
                <Label>失效日期</Label>
                <Input
                  type="date"
                  value={createForm.expiryDate || ''}
                  onChange={event => setCreateForm(prev => ({ ...prev, expiryDate: event.target.value }))}
                />
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <Button variant="outline" onClick={resetCreateDialog}>取消</Button>
              <Button disabled={actionLoading} onClick={() => void handleCreate()}>保存编制</Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default HrHeadcountPage;

// cloudflow-frontend-vue/src/pages/hr/HrHeadcountPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { BarChart3, Layers3, Plus, RefreshCcw, Save, Target } from 'lucide-vue-next'
import {
  BaseDialog,
  Button,
  DataTable,
  Input,
  Panel,
  Select,
  StatusBadge,
  type Column,
  type SelectOption
} from '@/components/common'
import {
  type DeptTreeNode,
  type Headcount,
  type HeadcountStatistics,
  type PostOption,
  getDeptTreeOptions,
  getHeadcountStatistics,
  getPostOptions,
  listHeadcounts,
  setHeadcount,
  updateHeadcountActualCount
} from '@/services/api/hr'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errorMessage'
import { flattenDeptTree, formatDate, formatNumber, normalizeRows, statusTone, todayValue } from './hrUtils'

const toast = useToastStore()
const loading = ref(false)
const submitting = ref(false)
const dialogOpen = ref(false)
const keyword = ref('')
const selectedHeadcount = ref<Headcount | null>(null)
const statistics = ref<HeadcountStatistics | null>(null)
const headcounts = ref<Headcount[]>([])
const deptOptions = ref<DeptTreeNode[]>([])
const postOptions = ref<PostOption[]>([])

const form = ref({
  targetType: 'DEPT',
  targetId: '',
  approvedCount: '1',
  actualCount: '0',
  effectiveDate: todayValue(),
  expiryDate: ''
})

const columns: Column<Headcount>[] = [
  { key: 'targetName', label: '组织对象' },
  { key: 'approvedCount', label: '核定编制', sortable: true },
  { key: 'actualCount', label: '实际人数', sortable: true },
  { key: 'vacancyCount', label: '空缺', sortable: true },
  { key: 'effectiveDate', label: '有效期' },
  { key: 'actions', label: '操作', class: 'text-right' }
]

const targetTypeOptions: SelectOption[] = [
  { value: 'DEPT', label: '部门' },
  { value: 'POST', label: '岗位' }
]

const deptSelectOptions = computed<SelectOption[]>(() =>
  flattenDeptTree(deptOptions.value).map((item) => ({ value: item.deptId, label: item.deptName }))
)

const postSelectOptions = computed<SelectOption[]>(() =>
  normalizeRows<PostOption>(postOptions.value).map((item) => ({ value: item.postId, label: item.postName }))
)

const targetOptions = computed(() => form.value.targetType === 'DEPT' ? deptSelectOptions.value : postSelectOptions.value)

const filteredHeadcounts = computed(() => {
  const q = keyword.value.trim().toLowerCase()
  if (!q) return headcounts.value
  return headcounts.value.filter((item) =>
    [item.targetType, item.targetName, item.targetId].some((value) =>
      String(value || '').toLowerCase().includes(q)
    )
  )
})

const summary = computed(() => {
  const approved = headcounts.value.reduce((sum, item) => sum + Number(item.approvedCount || 0), 0)
  const actual = headcounts.value.reduce((sum, item) => sum + Number(item.actualCount || 0), 0)
  const vacancy = headcounts.value.reduce((sum, item) => sum + Number(item.vacancyCount || 0), 0)
  const overstaffed = headcounts.value.filter((item) => Number(item.vacancyCount || 0) < 0).length
  return { approved, actual, vacancy, overstaffed }
})

const vacancyTone = (item: Headcount) => {
  if (Number(item.vacancyCount || 0) < 0) return 'red'
  if (Number(item.vacancyCount || 0) > 0) return 'yellow'
  return 'green'
}

const loadOptions = async () => {
  const [deptRes, postRes] = await Promise.allSettled([getDeptTreeOptions(), getPostOptions()])
  deptOptions.value = deptRes.status === 'fulfilled' ? normalizeRows<DeptTreeNode>(deptRes.value) : []
  postOptions.value = postRes.status === 'fulfilled' ? normalizeRows<PostOption>(postRes.value) : []
}

const loadData = async () => {
  loading.value = true
  try {
    headcounts.value = normalizeRows<Headcount>(await listHeadcounts())
    if (!selectedHeadcount.value && headcounts.value.length) await selectHeadcount(headcounts.value[0])
  } catch (error) {
    toast.error(getErrorMessage(error, '编制数据加载失败'))
  } finally {
    loading.value = false
  }
}

const selectHeadcount = async (item: Headcount) => {
  selectedHeadcount.value = item
  try {
    statistics.value = await getHeadcountStatistics(item.targetType, item.targetId)
  } catch {
    statistics.value = null
  }
}

const openDialog = (item?: Headcount) => {
  form.value = {
    targetType: item?.targetType || 'DEPT',
    targetId: String(item?.targetId || ''),
    approvedCount: String(item?.approvedCount ?? 1),
    actualCount: String(item?.actualCount ?? 0),
    effectiveDate: formatDate(item?.effectiveDate, todayValue()),
    expiryDate: formatDate(item?.expiryDate, '')
  }
  dialogOpen.value = true
}

const handleSave = async () => {
  submitting.value = true
  try {
    const targetType = form.value.targetType
    const targetId = Number(form.value.targetId)
    await setHeadcount({
      targetType,
      targetId,
      approvedCount: Number(form.value.approvedCount || 0),
      effectiveDate: form.value.effectiveDate || undefined,
      expiryDate: form.value.expiryDate || undefined
    })
    if (form.value.actualCount !== '') {
      await updateHeadcountActualCount(targetType, targetId, Number(form.value.actualCount || 0))
    }
    dialogOpen.value = false
    toast.success('保存成功')
    await loadData()
  } catch (error) {
    toast.error(getErrorMessage(error, '保存失败'))
  } finally {
    submitting.value = false
  }
}

onMounted(async () => {
  await Promise.all([loadOptions(), loadData()])
})
</script>

<template>
  <div class="space-y-4">
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div>
        <div class="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.16em] text-slate-400 dark:text-slate-500">
          <Layers3 class="h-3.5 w-3.5 text-cyan-600 dark:text-cyan-300" />
          Headcount Control
        </div>
        <h1 class="mt-1.5 text-[26px] font-semibold tracking-tight text-slate-900 dark:text-slate-100">编制管理</h1>
      </div>
      <div class="flex flex-wrap gap-2">
        <Button variant="outline" :disabled="loading" @click="loadData"><RefreshCcw class="h-4 w-4" :class="loading ? 'animate-spin' : ''" />刷新</Button>
        <Button @click="openDialog()"><Plus class="h-4 w-4" />设置编制</Button>
      </div>
    </div>

    <div class="grid gap-4 md:grid-cols-4">
      <div class="card p-4"><div class="text-xs text-slate-500">核定编制</div><div class="mt-2 text-2xl font-semibold">{{ formatNumber(summary.approved) }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">实际在职</div><div class="mt-2 text-2xl font-semibold">{{ formatNumber(summary.actual) }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">空缺人数</div><div class="mt-2 text-2xl font-semibold">{{ formatNumber(summary.vacancy) }}</div></div>
      <div class="card p-4"><div class="text-xs text-slate-500">超编对象</div><div class="mt-2 text-2xl font-semibold">{{ formatNumber(summary.overstaffed) }}</div></div>
    </div>

    <div class="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,0.8fr)]">
      <Panel title="编制清单">
        <template #icon><Target class="h-4 w-4 text-slate-500" /></template>
        <div class="mb-4 max-w-md"><Input v-model="keyword" placeholder="搜索部门、岗位、类型" /></div>
        <DataTable :columns="columns" :data="filteredHeadcounts" :loading="loading" row-key="id">
          <template #cell-targetName="{ row }">
            <button type="button" class="text-left" @click="selectHeadcount(row)">
              <div class="font-semibold">{{ row.targetName || row.targetId }}</div>
              <div class="text-xs text-slate-500">{{ row.targetType === 'DEPT' ? '部门' : '岗位' }}</div>
            </button>
          </template>
          <template #cell-vacancyCount="{ row }"><StatusBadge :label="String(row.vacancyCount ?? 0)" :tone="vacancyTone(row)" /></template>
          <template #cell-effectiveDate="{ row }">{{ formatDate(row.effectiveDate) }} ~ {{ formatDate(row.expiryDate, '长期有效') }}</template>
          <template #cell-actions="{ row }">
            <div class="flex justify-end gap-1">
              <Button size="sm" :variant="selectedHeadcount?.id === row.id ? 'primary' : 'outline'" @click="selectHeadcount(row)">详情</Button>
              <Button size="icon" variant="ghost" @click="openDialog(row)"><Save class="h-4 w-4" /></Button>
            </div>
          </template>
        </DataTable>
      </Panel>

      <Panel title="编制详情">
        <template #icon><BarChart3 class="h-4 w-4 text-slate-500" /></template>
        <div v-if="selectedHeadcount" class="space-y-3">
          <div class="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900/40">
            <div class="text-sm font-semibold text-slate-900 dark:text-slate-100">{{ selectedHeadcount.targetName || selectedHeadcount.targetId }}</div>
            <div class="mt-1 text-xs text-slate-500">{{ selectedHeadcount.targetType }} · {{ formatDate(selectedHeadcount.effectiveDate) }}</div>
          </div>
          <div class="grid gap-3 sm:grid-cols-3">
            <div class="card p-3"><div class="text-xs text-slate-500">核定</div><div class="mt-1 text-xl font-semibold">{{ statistics?.approvedCount ?? selectedHeadcount.approvedCount }}</div></div>
            <div class="card p-3"><div class="text-xs text-slate-500">实际</div><div class="mt-1 text-xl font-semibold">{{ statistics?.actualCount ?? selectedHeadcount.actualCount }}</div></div>
            <div class="card p-3"><div class="text-xs text-slate-500">利用率</div><div class="mt-1 text-xl font-semibold">{{ statistics?.utilizationRate ?? '-' }}</div></div>
          </div>
          <StatusBadge :label="(statistics?.isOverstaffed || Number(selectedHeadcount.vacancyCount) < 0) ? '超编' : '正常'" :tone="(statistics?.isOverstaffed || Number(selectedHeadcount.vacancyCount) < 0) ? 'red' : statusTone('ACTIVE')" />
        </div>
        <div v-else class="py-12 text-center text-sm text-slate-500">请选择编制记录</div>
      </Panel>
    </div>

    <BaseDialog :show="dialogOpen" title="设置编制" width="wide" @close="dialogOpen = false">
      <div class="grid gap-4 md:grid-cols-2">
        <label class="space-y-2"><span class="text-sm font-medium">对象类型</span><Select v-model="form.targetType" :options="targetTypeOptions" /></label>
        <label class="space-y-2"><span class="text-sm font-medium">对象</span><Select v-model="form.targetId" :options="targetOptions" searchable /></label>
        <Input v-model="form.approvedCount" label="核定编制" type="number" />
        <Input v-model="form.actualCount" label="实际人数" type="number" />
        <Input v-model="form.effectiveDate" label="生效日期" type="date" />
        <Input v-model="form.expiryDate" label="失效日期" type="date" />
      </div>
      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="dialogOpen = false">取消</Button>
          <Button :disabled="submitting" @click="handleSave"><Save class="h-4 w-4" />保存</Button>
        </div>
      </template>
    </BaseDialog>
  </div>
</template>
