// cloudflow-frontend-tauri/src/pages/admin/attendance/AttendanceCheckIn.tsx
import React, { useEffect, useMemo, useState } from 'react';
import {
  AlertCircle,
  Calendar,
  CheckCircle2,
  Clock3,
  LogIn,
  LogOut,
  MapPin,
  RefreshCw,
} from 'lucide-react';
import { Button } from '@/components/common';
import { checkIn } from '@/services/api/admin';
import { EffectiveAttendanceRule, getEffectiveAttendanceRule } from '@/services/api/hr';
import { useAuth } from '@/context/AuthContext';
import { useHrSelfServiceEligibility } from '@/hooks/useHrSelfServiceEligibility';
import { useMount } from '@/hooks/useMount';

const formatDateCN = (date: Date) => {
  const weekdays = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'];
  return `${date.getMonth() + 1}月${date.getDate()}日 ${weekdays[date.getDay()]}`;
};

const buildTimeDate = (time: string, base: Date) => {
  const [hours = '00', minutes = '00'] = (time || '').split(':');
  const result = new Date(base);
  result.setHours(Number(hours), Number(minutes), 0, 0);
  return result;
};

const InlineState = ({
  title,
  description,
  icon,
  className,
}: {
  title: string;
  description?: string;
  icon?: React.ReactNode;
  className?: string;
}) => (
  <div className={['flex flex-col items-center justify-center px-6 py-10 text-center', className].filter(Boolean).join(' ')}>
    <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-slate-50 text-slate-400 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-500">
      {icon || <Clock3 className="h-4 w-4" />}
    </div>
    <div className="text-sm font-medium text-slate-900 dark:text-slate-100">{title}</div>
    {description ? <div className="mt-2 text-xs leading-6 text-slate-500 dark:text-slate-400">{description}</div> : null}
  </div>
);

const SideItem = ({
  label,
  value,
  description,
  icon,
}: {
  label: string;
  value: string;
  description?: string;
  icon: React.ReactNode;
}) => (
  <div className="flex gap-3 px-4 py-3">
    <div className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-slate-500 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400">
      {icon}
    </div>
    <div className="min-w-0 flex-1">
      <div className="text-[11px] font-medium text-slate-400 dark:text-slate-500">{label}</div>
      <div className="mt-0.5 truncate text-sm font-medium text-slate-900 dark:text-slate-100">{value}</div>
      {description ? (
        <div className="mt-0.5 truncate text-xs text-slate-500 dark:text-slate-400">{description}</div>
      ) : null}
    </div>
  </div>
);

const ActionButton = ({
  title,
  icon,
  onClick,
  disabled,
  variant = 'default',
}: {
  title: string;
  icon: React.ReactNode;
  onClick: () => void;
  disabled: boolean;
  variant?: 'default' | 'outline' | 'destructive';
}) => (
  <Button
    variant={variant}
    className="h-12 justify-start rounded-xl px-4 text-left"
    onClick={onClick}
    disabled={disabled}
  >
    <div className="flex items-center gap-3">
      <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-current/10 bg-white/70 text-current dark:bg-slate-950/30">
        {icon}
      </div>
      <div className="text-sm font-semibold">{title}</div>
    </div>
  </Button>
);

const AttendanceCheckIn: React.FC = () => {
  const { user } = useAuth();
  const [currentTime, setCurrentTime] = useState(new Date());
  const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null);
  const [locationError, setLocationError] = useState<string | null>(null);
  const [rule, setRule] = useState<EffectiveAttendanceRule | null>(null);
  const [ruleLoading, setRuleLoading] = useState(true);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ success: boolean; msg: string } | null>(null);
  const [autoLocationRequested, setAutoLocationRequested] = useState(false);
  const {
    loading: eligibilityLoading,
    canStartSelfService,
    restrictionMessage,
  } = useHrSelfServiceEligibility();

  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  useMount(() => {
    void getEffectiveAttendanceRule()
      .then((response) => {
        setRule(response || null);
      })
      .catch(() => {
        setRule(null);
      })
      .finally(() => {
        setRuleLoading(false);
      });
  });

  const getLocation = () => {
    if (eligibilityLoading) {
      return;
    }
    if (!canStartSelfService) {
      setLocationError(restrictionMessage || '当前账号暂不能继续发起 HR 自助流程');
      return;
    }
    if (!navigator.geolocation) {
      setLocationError('您的浏览器不支持地理定位');
      return;
    }

    setLocationError(null);
    setLoading(true);
    navigator.geolocation.getCurrentPosition(
      (position) => {
        setLocation({
          lat: position.coords.latitude,
          lng: position.coords.longitude,
        });
        setLocationError(null);
        setLoading(false);
      },
      (error) => {
        setLocationError(`获取位置失败: ${error.message}`);
        setLoading(false);
      },
      { enableHighAccuracy: true, timeout: 5000, maximumAge: 0 },
    );
  };

  useEffect(() => {
    if (autoLocationRequested || eligibilityLoading || !canStartSelfService) {
      return;
    }
    setAutoLocationRequested(true);
    getLocation();
  }, [autoLocationRequested, canStartSelfService, eligibilityLoading]);

  const selfServiceLocked = eligibilityLoading || !canStartSelfService;

  const ensureCanCheckIn = () => {
    if (eligibilityLoading) {
      setResult({ success: false, msg: '正在核对当前员工状态，请稍后再试' });
      return false;
    }
    if (!canStartSelfService) {
      setResult({ success: false, msg: restrictionMessage || '当前账号暂不能继续发起 HR 自助流程' });
      return false;
    }
    return true;
  };

  const handleCheckIn = async (type: '1' | '2') => {
    if (!ensureCanCheckIn()) {
      return;
    }
    if (!location) {
      setResult({ success: false, msg: '请先获取定位信息' });
      return;
    }

    setLoading(true);
    try {
      await checkIn({
        type,
        location: `${location.lat},${location.lng}`,
        address: 'Web端定位',
        deviceInfo: navigator.userAgent,
        wifiInfo: 'Web端无法获取Mac',
      });
      setResult({ success: true, msg: type === '1' ? '签到成功' : '签退成功' });
    } catch (error) {
      setResult({ success: false, msg: error instanceof Error ? error.message : '打卡失败，请重试' });
    } finally {
      setLoading(false);
    }
  };

  const dateLabel = formatDateCN(currentTime);
  const timeLabel = currentTime.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });
  const secondLabel = currentTime.toLocaleTimeString('zh-CN', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  });
  const shiftLabel = `${rule?.checkInTime || '--:--'} - ${rule?.checkOutTime || '--:--'}`;
  const sourceLabel =
    rule?.sourceType === 'EMPLOYEE'
      ? `员工规则 ${rule.sourceTargetName || ''}`
      : rule?.sourceType === 'POST'
        ? `岗位规则 ${rule.sourceTargetName || ''}`
        : rule?.sourceType === 'DEPT'
          ? `部门规则 ${rule.sourceTargetName || ''}`
          : '默认规则';
  const dayTypeLabel =
    rule?.dayType === 'WORKDAY'
      ? '工作日'
      : rule?.dayType === 'HOLIDAY'
        ? '节假日'
        : rule?.dayType === 'REST'
          ? '休息日'
          : '未设置日历';
  const methodLabel = rule?.checkMethods?.join(' / ') || '--';

  const phaseInfo = useMemo(() => {
    if (ruleLoading) {
      return {
        title: '规则加载中',
        hint: '正在同步今日考勤规则',
      };
    }

    if (!rule) {
      return {
        title: '未配置考勤规则',
        hint: '当前未读取到有效考勤规则，请联系 HR 检查班次与规则配置',
      };
    }

    const now = currentTime.getTime();
    const checkInTime = buildTimeDate(rule.checkInTime || '09:00', currentTime).getTime();
    const checkOutTime = buildTimeDate(rule.checkOutTime || '18:00', currentTime).getTime();

    if (now < checkInTime) {
      return {
        title: '上班前准备',
        hint: `距离上班时间 ${rule.checkInTime} 还有安排空间`,
      };
    }
    if (now >= checkInTime && now < checkOutTime) {
      return {
        title: '工作时段',
        hint: '当前处于上班到下班之间，可进行签到或补充定位',
      };
    }
    return {
      title: '下班签退时段',
      hint: `当前已过下班时间 ${rule.checkOutTime}，请确认是否需要签退`,
    };
  }, [currentTime, rule, ruleLoading]);

  const locationStatus = location
    ? {
        title: '定位已准备',
        hint: `${location.lat.toFixed(4)}, ${location.lng.toFixed(4)}`,
      }
    : {
        title: loading ? '正在定位' : '定位待处理',
        hint: loading ? '正在获取当前坐标信息' : (locationError || '请先获取定位信息'),
      };
  const locationSummary = location ? '定位已就绪' : '待定位';
  const locationDetail = location ? `${location.lat.toFixed(4)}, ${location.lng.toFixed(4)}` : locationStatus.title;

  if (ruleLoading) {
    return (
      <div className="space-y-4">
        <div className="min-w-0">
          <div className="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.16em] text-slate-400 dark:text-slate-500">
            <Clock3 className="h-3.5 w-3.5 text-cyan-600 dark:text-cyan-300" />
            Attendance Check-In
          </div>
          <h1 className="mt-1.5 text-[26px] font-semibold tracking-tight text-slate-900 dark:text-slate-100">
            考勤打卡
          </h1>
        </div>
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950/88">
          <InlineState title="正在加载考勤规则..." className="py-16" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="min-w-0">
        <div className="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.16em] text-slate-400 dark:text-slate-500">
          <Clock3 className="h-3.5 w-3.5 text-cyan-600 dark:text-cyan-300" />
          Attendance Check-In
        </div>
        <h1 className="mt-1.5 text-[26px] font-semibold tracking-tight text-slate-900 dark:text-slate-100">
          考勤打卡
        </h1>
      </div>

      <div className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm dark:border-slate-800 dark:bg-slate-950/88">
        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
          {dateLabel}
        </span>
        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
          规则 {rule?.ruleName || '未配置'}
        </span>
        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
          {dayTypeLabel}
        </span>
        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
          {locationSummary}
        </span>

        <div className="ml-auto flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={getLocation} disabled={loading || selfServiceLocked}>
            <RefreshCw size={14} className={loading ? 'mr-1.5 animate-spin' : 'mr-1.5'} />
            {loading ? '定位中...' : '刷新定位'}
          </Button>
        </div>
      </div>

      {restrictionMessage ? (
        <div
          data-testid="hr-self-service-restriction"
          className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-4 text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"
        >
          <div className="flex items-start gap-3">
            <div className="rounded-full border border-amber-200 bg-white p-2 text-amber-600 dark:border-amber-800 dark:bg-amber-950/20 dark:text-amber-300">
              <AlertCircle size={16} />
            </div>
            <div>
              <div className="text-sm font-semibold">当前账号暂不能继续发起 HR 自助流程</div>
              <div className="mt-1 text-xs leading-6">{restrictionMessage}</div>
            </div>
          </div>
        </div>
      ) : null}

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]">
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950/88">
          <div className="border-b border-slate-200 px-5 py-4 dark:border-slate-800">
            <div className="flex items-center justify-between gap-3">
              <div>
                <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">{user?.name || '当前员工'}</div>
                <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">{phaseInfo.title}</div>
              </div>
              <div className="text-xs text-slate-500 dark:text-slate-400">{timeLabel}</div>
            </div>
          </div>

          <div className="space-y-4 p-5">
            <div className="rounded-xl border border-slate-200 bg-slate-50/80 p-5 dark:border-slate-800 dark:bg-slate-900/60">
              <div className="text-[40px] font-semibold leading-none tracking-[0.08em] text-slate-900 dark:text-slate-100">
                {secondLabel}
              </div>
              <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500 dark:text-slate-400">
                <span>{dateLabel}</span>
                <span>{shiftLabel}</span>
              </div>
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              <ActionButton
                title="上班打卡"
                icon={<LogIn size={16} />}
                onClick={() => handleCheckIn('1')}
                disabled={loading || !location || selfServiceLocked}
              />
              <ActionButton
                title="下班签退"
                icon={<LogOut size={16} />}
                onClick={() => handleCheckIn('2')}
                disabled={loading || !location || selfServiceLocked}
                variant="destructive"
              />
            </div>

            <div className="rounded-xl border border-slate-200 bg-white px-4 py-3.5 dark:border-slate-800 dark:bg-slate-950">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex min-w-0 items-center gap-3">
                  <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-slate-500 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400">
                    <MapPin size={15} />
                  </div>
                  <div className="min-w-0">
                    <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">{locationStatus.title}</div>
                    {locationError || location ? (
                      <div className="mt-1 truncate text-xs text-slate-500 dark:text-slate-400">{locationStatus.hint}</div>
                    ) : null}
                  </div>
                </div>
                <div className="text-xs text-slate-500 dark:text-slate-400">{locationSummary}</div>
              </div>
            </div>

            <div
              className={`rounded-xl border px-4 py-4 text-sm leading-6 ${
                result
                  ? result.success
                    ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200'
                    : 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200'
                  : 'border-slate-200 bg-slate-50 text-slate-500 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-400'
              }`}
            >
              {result ? (
                <div className="flex items-start gap-3">
                  <div className="mt-0.5">
                    {result.success ? <CheckCircle2 size={16} /> : <AlertCircle size={16} />}
                  </div>
                  <div>
                    <div className="font-semibold">{result.success ? '打卡成功' : '打卡失败'}</div>
                    <div className="mt-1">{result.msg}</div>
                  </div>
                </div>
              ) : (
                <div>
                  <div className="font-semibold text-slate-700 dark:text-slate-200">等待打卡</div>
                  <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">完成定位后可直接签到或签退。</div>
                </div>
              )}
            </div>
          </div>
        </section>

        <aside className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950/88">
          <div className="border-b border-slate-200 px-5 py-4 dark:border-slate-800">
            <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">今日规则</div>
          </div>

          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            <SideItem
              label="当前阶段"
              value={phaseInfo.title}
              icon={<Calendar size={15} />}
            />
            <SideItem
              label="规则来源"
              value={sourceLabel}
              description={rule?.ruleName}
              icon={<CheckCircle2 size={15} />}
            />
            <SideItem
              label="允许方式"
              value={methodLabel}
              description={`半径 ${rule?.radius ?? '--'} 米`}
              icon={<MapPin size={15} />}
            />
            <SideItem
              label="定位状态"
              value={locationDetail}
              icon={<MapPin size={15} />}
            />
            <SideItem
              label="签到时间"
              value={rule?.checkInTime || '--:--'}
              icon={<LogIn size={15} />}
            />
            <SideItem
              label="签退时间"
              value={rule?.checkOutTime || '--:--'}
              icon={<LogOut size={15} />}
            />
          </div>
        </aside>
      </div>
    </div>
  );
};

export default AttendanceCheckIn;

// cloudflow-frontend-vue/src/pages/admin/attendance/AttendanceCheckIn.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import {
  AlertCircle,
  Calendar,
  CheckCircle2,
  Clock3,
  Fingerprint,
  LogIn,
  LogOut,
  MapPin,
  RefreshCw,
  Wifi
} from 'lucide-vue-next'
import { Button, DataTable, Input, Panel, Select, StatusBadge, type Column, type SelectOption } from '@/components/common'
import {
  type EffectiveAttendanceRule,
  type HrAttendanceRecord,
  type HrEmployee,
  getEffectiveAttendanceRule,
  getHrSelfServiceRestrictionMessage,
  hrCheckIn,
  hrCheckOut,
  listHrAttendanceRecords,
  resolveCurrentEmployee
} from '@/services/api/hr'
import { useAuthStore } from '@/stores/auth'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errorMessage'

type CheckMethod = 'GPS' | 'WIFI' | 'FACE'

const CHECK_METHOD_LABEL: Record<string, string> = {
  GPS: 'GPS 定位',
  WIFI: 'Wi-Fi',
  FACE: '人脸识别',
  SUPPLEMENT: '补卡'
}

const CHECK_TYPE_LABEL: Record<string, string> = {
  CHECK_IN: '上班打卡',
  CHECK_OUT: '下班签退'
}

const DAY_TYPE_LABEL: Record<string, string> = {
  WORKDAY: '工作日',
  REST: '休息日',
  HOLIDAY: '节假日'
}

const STATUS_LABEL: Record<string, string> = {
  NORMAL: '正常',
  LATE: '迟到',
  SEVERE_LATE: '严重迟到',
  EARLY: '早退',
  ABSENT: '旷工',
  MISSING: '缺卡',
  SUPPLEMENT: '补卡',
  APPROVING: '审批中',
  REJECTED: '已驳回'
}

const statusTone = (status?: string): 'slate' | 'green' | 'red' | 'yellow' | 'cyan' => {
  switch (status) {
    case 'NORMAL':
    case 'SUPPLEMENT':
      return 'green'
    case 'LATE':
    case 'SEVERE_LATE':
    case 'EARLY':
    case 'MISSING':
      return 'yellow'
    case 'ABSENT':
    case 'REJECTED':
      return 'red'
    case 'APPROVING':
      return 'cyan'
    default:
      return 'slate'
  }
}

const getCheckTypeLabel = (type?: string) => type ? (CHECK_TYPE_LABEL[type] || type) : '-'
const getCheckMethodLabel = (method?: string) => method ? (CHECK_METHOD_LABEL[method] || method) : '-'
const getStatusLabel = (status?: string) => status ? (STATUS_LABEL[status] || status) : '-'

const auth = useAuthStore()
const toast = useToastStore()

const now = ref(new Date())
const loading = ref(false)
const ruleLoading = ref(true)
const recordsLoading = ref(false)
const employee = ref<HrEmployee | null>(null)
const rule = ref<EffectiveAttendanceRule | null>(null)
const records = ref<HrAttendanceRecord[]>([])
const location = ref<{ latitude: number; longitude: number } | null>(null)
const locationError = ref('')
const selectedMethod = ref<CheckMethod>('GPS')
const wifiSsid = ref('')
const faceToken = ref('')
const remark = ref('')
const result = ref<{ success: boolean; message: string } | null>(null)

let timer: number | undefined

const recordColumns: Column<HrAttendanceRecord>[] = [
  { key: 'checkType', label: '类型' },
  { key: 'checkTime', label: '时间', sortable: true },
  { key: 'checkMethod', label: '方式' },
  { key: 'location', label: '位置' },
  { key: 'status', label: '状态' }
]

const formatDateInput = (date: Date) => {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

const formatDateCN = (date: Date) => {
  const weekdays = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
  return `${date.getMonth() + 1}月${date.getDate()}日 ${weekdays[date.getDay()]}`
}

const formatTime = (value?: string) => (value || '').slice(0, 5) || '--:--'
const formatDateTime = (value?: string) => value ? value.replace('T', ' ').slice(0, 19) : '-'

const today = computed(() => formatDateInput(now.value))
const currentTimeLabel = computed(() => now.value.toLocaleTimeString('zh-CN', { hour12: false }))
const currentMinuteLabel = computed(() => now.value.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }))
const dateLabel = computed(() => formatDateCN(now.value))
const selfServiceRestriction = computed(() => getHrSelfServiceRestrictionMessage(employee.value))
const selfServiceLocked = computed(() => loading.value || ruleLoading.value || Boolean(selfServiceRestriction.value))
const allowedMethods = computed(() => {
  const methods = rule.value?.checkMethods?.length ? rule.value.checkMethods : ['GPS']
  return methods.filter((method): method is CheckMethod => ['GPS', 'WIFI', 'FACE'].includes(method))
})
const methodOptions = computed<SelectOption[]>(() =>
  allowedMethods.value.map((method) => ({ value: method, label: CHECK_METHOD_LABEL[method] || method }))
)
const dayTypeLabel = computed(() => DAY_TYPE_LABEL[rule.value?.dayType || ''] || '未设置日历')
const shiftLabel = computed(() => `${formatTime(rule.value?.checkInTime)} - ${formatTime(rule.value?.checkOutTime)}`)
const sourceLabel = computed(() => {
  if (!rule.value) return '未配置'
  const target = rule.value.sourceTargetName ? ` ${rule.value.sourceTargetName}` : ''
  if (rule.value.sourceType === 'EMPLOYEE') return `员工规则${target}`
  if (rule.value.sourceType === 'POST') return `岗位规则${target}`
  if (rule.value.sourceType === 'DEPT') return `部门规则${target}`
  return '默认规则'
})

const phaseInfo = computed(() => {
  if (ruleLoading.value) return { title: '规则加载中', hint: '正在同步今日考勤规则' }
  if (!rule.value) return { title: '未配置规则', hint: '当前未读取到有效考勤规则' }

  const [inHour = '09', inMinute = '00'] = formatTime(rule.value.checkInTime).split(':')
  const [outHour = '18', outMinute = '00'] = formatTime(rule.value.checkOutTime).split(':')
  const checkInTime = new Date(now.value)
  checkInTime.setHours(Number(inHour), Number(inMinute), 0, 0)
  const checkOutTime = new Date(now.value)
  checkOutTime.setHours(Number(outHour), Number(outMinute), 0, 0)

  if (now.value.getTime() < checkInTime.getTime()) {
    return { title: '上班前准备', hint: `上班时间 ${formatTime(rule.value.checkInTime)}` }
  }
  if (now.value.getTime() < checkOutTime.getTime()) {
    return { title: '工作时段', hint: '可进行签到或刷新定位' }
  }
  return { title: '下班签退时段', hint: `下班时间 ${formatTime(rule.value.checkOutTime)}` }
})

const locationSummary = computed(() => {
  if (selectedMethod.value === 'GPS') {
    if (location.value) return `${location.value.latitude.toFixed(5)}, ${location.value.longitude.toFixed(5)}`
    return locationError.value || '待获取 GPS 定位'
  }
  if (selectedMethod.value === 'WIFI') return wifiSsid.value || '待输入 Wi-Fi SSID'
  return faceToken.value ? '人脸凭证已填写' : '待输入人脸凭证'
})

const canSubmit = computed(() => {
  if (selfServiceLocked.value || !rule.value) return false
  if (selectedMethod.value === 'GPS') return Boolean(location.value)
  if (selectedMethod.value === 'WIFI') return Boolean(wifiSsid.value.trim())
  if (selectedMethod.value === 'FACE') return Boolean(faceToken.value.trim())
  return false
})

const loadRecords = async () => {
  if (!employee.value?.id) return
  recordsLoading.value = true
  try {
    records.value = await listHrAttendanceRecords({
      employeeId: employee.value.id,
      startDate: today.value,
      endDate: today.value,
      pageNum: 1,
      pageSize: 20
    })
  } catch (error) {
    toast.error(getErrorMessage(error, '加载今日打卡记录失败'))
  } finally {
    recordsLoading.value = false
  }
}

const loadAll = async () => {
  ruleLoading.value = true
  result.value = null
  try {
    const currentEmployee = await resolveCurrentEmployee()
    employee.value = currentEmployee
    const effectiveRule = await getEffectiveAttendanceRule({ employeeId: currentEmployee.id, date: today.value })
    rule.value = effectiveRule || null
    const firstAllowed = effectiveRule?.checkMethods?.find((method) => ['GPS', 'WIFI', 'FACE'].includes(method))
    selectedMethod.value = (firstAllowed as CheckMethod | undefined) || 'GPS'
    await loadRecords()
  } catch (error) {
    rule.value = null
    employee.value = null
    toast.error(getErrorMessage(error, '加载考勤信息失败'))
  } finally {
    ruleLoading.value = false
  }
}

const getLocation = () => {
  if (selfServiceRestriction.value) {
    locationError.value = selfServiceRestriction.value
    return
  }
  if (!navigator.geolocation) {
    locationError.value = '当前浏览器不支持地理定位'
    return
  }

  loading.value = true
  locationError.value = ''
  navigator.geolocation.getCurrentPosition(
    (position) => {
      location.value = {
        latitude: position.coords.latitude,
        longitude: position.coords.longitude
      }
      loading.value = false
    },
    (error) => {
      location.value = null
      locationError.value = `获取位置失败：${error.message}`
      loading.value = false
    },
    { enableHighAccuracy: true, timeout: 7000, maximumAge: 0 }
  )
}

const buildPayload = () => {
  const payload = {
    checkMethod: selectedMethod.value,
    remark: remark.value.trim() || undefined
  }
  if (selectedMethod.value === 'GPS') {
    return {
      ...payload,
      location: location.value ? `${location.value.latitude},${location.value.longitude}` : undefined,
      latitude: location.value?.latitude,
      longitude: location.value?.longitude
    }
  }
  if (selectedMethod.value === 'WIFI') {
    return {
      ...payload,
      location: wifiSsid.value.trim(),
      wifiSsid: wifiSsid.value.trim()
    }
  }
  return {
    ...payload,
    faceToken: faceToken.value.trim()
  }
}

const submitCheck = async (type: 'CHECK_IN' | 'CHECK_OUT') => {
  if (!canSubmit.value) {
    result.value = { success: false, message: '请先完成当前打卡方式所需信息' }
    return
  }

  loading.value = true
  result.value = null
  try {
    if (type === 'CHECK_IN') {
      await hrCheckIn(buildPayload())
    } else {
      await hrCheckOut(buildPayload())
    }
    result.value = { success: true, message: `${CHECK_TYPE_LABEL[type]}成功` }
    toast.success(`${CHECK_TYPE_LABEL[type]}成功`)
    await loadRecords()
  } catch (error) {
    const message = getErrorMessage(error, '打卡失败')
    result.value = { success: false, message }
    toast.error(message)
  } finally {
    loading.value = false
  }
}

watch(selectedMethod, (method) => {
  result.value = null
  if (method === 'GPS' && !location.value) getLocation()
})

onMounted(() => {
  timer = window.setInterval(() => {
    now.value = new Date()
  }, 1000)
  void loadAll().then(() => {
    if (selectedMethod.value === 'GPS') getLocation()
  })
})

onUnmounted(() => {
  if (timer) window.clearInterval(timer)
})
</script>

<template>
  <div class="space-y-5">
    <div class="page-header">
      <div class="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.16em] text-gray-400 dark:text-dark-400">
        <Clock3 class="h-3.5 w-3.5 text-primary-600 dark:text-primary-400" />
        Attendance Check-In
      </div>
      <h1 class="page-title mt-1.5">考勤打卡</h1>
      <p class="page-description">{{ dateLabel }} · {{ currentMinuteLabel }} · {{ phaseInfo.title }}</p>
    </div>

    <div v-if="selfServiceRestriction" class="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">
      <AlertCircle class="mt-0.5 h-4 w-4 shrink-0" />
      <span>{{ selfServiceRestriction }}</span>
    </div>

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <section class="card overflow-hidden">
        <div class="card-header flex flex-wrap items-center justify-between gap-3">
          <div>
            <div class="text-sm font-semibold text-gray-900 dark:text-white">{{ employee?.name || auth.user?.name || '当前员工' }}</div>
            <div class="mt-1 text-xs text-gray-500 dark:text-dark-400">{{ phaseInfo.hint }}</div>
          </div>
          <Button variant="outline" size="sm" :disabled="loading || ruleLoading" @click="loadAll">
            <RefreshCw class="h-3.5 w-3.5" :class="loading || ruleLoading ? 'animate-spin' : ''" />
            刷新
          </Button>
        </div>

        <div class="card-body space-y-5">
          <div class="rounded-2xl border border-gray-100 bg-gray-50/80 p-5 dark:border-dark-700 dark:bg-dark-900/60">
            <div class="text-[42px] font-semibold leading-none tracking-[0.08em] text-gray-900 dark:text-white">{{ currentTimeLabel }}</div>
            <div class="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-gray-500 dark:text-dark-400">
              <span>{{ dateLabel }}</span>
              <span>{{ shiftLabel }}</span>
            </div>
          </div>

          <div class="grid gap-4 lg:grid-cols-[220px_minmax(0,1fr)]">
            <label class="space-y-2">
              <span class="input-label">打卡方式</span>
              <Select v-model="selectedMethod" :options="methodOptions" />
            </label>

            <div class="space-y-2">
              <span class="input-label">打卡凭据</span>
              <div v-if="selectedMethod === 'GPS'" class="flex flex-wrap items-center gap-3 rounded-xl border border-gray-200 bg-white px-4 py-3 dark:border-dark-700 dark:bg-dark-800/70">
                <MapPin class="h-4 w-4 shrink-0 text-primary-600 dark:text-primary-400" />
                <div class="min-w-0 flex-1 text-sm text-gray-700 dark:text-gray-200">{{ locationSummary }}</div>
                <Button variant="outline" size="sm" :disabled="loading || Boolean(selfServiceRestriction)" @click="getLocation">
                  <RefreshCw class="h-3.5 w-3.5" :class="loading ? 'animate-spin' : ''" />
                  定位
                </Button>
              </div>
              <Input v-else-if="selectedMethod === 'WIFI'" v-model="wifiSsid" placeholder="输入当前 Wi-Fi SSID" />
              <Input v-else v-model="faceToken" placeholder="输入人脸识别凭证" />
            </div>
          </div>

          <Input v-model="remark" label="备注" placeholder="可选" />

          <div class="grid gap-3 sm:grid-cols-2">
            <Button class="h-14 justify-start" :disabled="!canSubmit || loading" @click="submitCheck('CHECK_IN')">
              <span class="flex h-9 w-9 items-center justify-center rounded-xl border border-white/20 bg-white/15">
                <LogIn class="h-4 w-4" />
              </span>
              上班打卡
            </Button>
            <Button class="h-14 justify-start" variant="danger" :disabled="!canSubmit || loading" @click="submitCheck('CHECK_OUT')">
              <span class="flex h-9 w-9 items-center justify-center rounded-xl border border-white/20 bg-white/15">
                <LogOut class="h-4 w-4" />
              </span>
              下班签退
            </Button>
          </div>

          <div
            class="rounded-xl border px-4 py-4 text-sm leading-6"
            :class="result ? (result.success ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200' : 'border-red-200 bg-red-50 text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200') : 'border-gray-200 bg-gray-50 text-gray-500 dark:border-dark-700 dark:bg-dark-900/60 dark:text-dark-400'"
          >
            <div class="flex items-start gap-3">
              <CheckCircle2 v-if="result?.success" class="mt-0.5 h-4 w-4" />
              <AlertCircle v-else-if="result" class="mt-0.5 h-4 w-4" />
              <Clock3 v-else class="mt-0.5 h-4 w-4" />
              <div>
                <div class="font-semibold">{{ result ? (result.success ? '打卡成功' : '打卡失败') : '等待打卡' }}</div>
                <div class="mt-1 text-xs">{{ result?.message || '完成打卡方式凭据后可提交。' }}</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <aside class="space-y-5">
        <Panel title="今日规则">
          <template #icon><Calendar class="h-4 w-4 text-gray-500" /></template>
          <div class="space-y-3 text-sm">
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">规则</span><span class="font-medium text-gray-900 dark:text-white">{{ rule?.ruleName || '-' }}</span></div>
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">来源</span><span class="font-medium text-gray-900 dark:text-white">{{ sourceLabel }}</span></div>
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">日历</span><StatusBadge :label="dayTypeLabel" tone="cyan" /></div>
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">班次</span><span class="font-medium text-gray-900 dark:text-white">{{ rule?.shiftName || '-' }}</span></div>
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">时间</span><span class="font-medium text-gray-900 dark:text-white">{{ shiftLabel }}</span></div>
            <div class="flex items-center justify-between gap-3"><span class="text-gray-500 dark:text-dark-400">半径</span><span class="font-medium text-gray-900 dark:text-white">{{ rule?.radius ?? '-' }} 米</span></div>
            <div class="flex flex-wrap gap-2 pt-1">
              <span v-for="method in rule?.checkMethods || []" :key="method" class="badge badge-primary">
                <MapPin v-if="method === 'GPS'" class="h-3 w-3" />
                <Wifi v-else-if="method === 'WIFI'" class="h-3 w-3" />
                <Fingerprint v-else class="h-3 w-3" />
                {{ CHECK_METHOD_LABEL[method] || method }}
              </span>
            </div>
          </div>
        </Panel>

        <Panel title="今日记录">
          <template #icon><Clock3 class="h-4 w-4 text-gray-500" /></template>
          <DataTable :columns="recordColumns" :data="records" :loading="recordsLoading" row-key="id" :sticky-first-column="false">
            <template #cell-checkType="{ row }">{{ getCheckTypeLabel(row.checkType) }}</template>
            <template #cell-checkTime="{ row }">{{ formatDateTime(row.checkTime) }}</template>
            <template #cell-checkMethod="{ row }">{{ getCheckMethodLabel(row.checkMethod) }}</template>
            <template #cell-location="{ row }">
              <span class="block max-w-[180px] truncate">{{ row.location || '-' }}</span>
            </template>
            <template #cell-status="{ row }">
              <StatusBadge :label="getStatusLabel(row.status)" :tone="statusTone(row.status)" />
            </template>
          </DataTable>
        </Panel>
      </aside>
    </div>
  </div>
</template>
