// cloudflow-frontend/src/components/TenantSwitcher.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Building2, Check, ChevronDown, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/context/AuthContext';
import { getTenantList } from '@/services/api/tenant';

interface Tenant {
  tenantId: number;
  tenantName: string;
  status: string;
}

const getTenantLabel = (tenantName?: string, tenantId?: number) => {
  const normalizedName = String(tenantName || '').trim();
  if (normalizedName) {
    return normalizedName;
  }

  if (typeof tenantId === 'number') {
    return `租户 ${tenantId}`;
  }

  return '默认租户';
};

export const TenantSwitcher: React.FC = () => {
  const { user, switchTenant } = useAuth();
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  const [tenants, setTenants] = useState<Tenant[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [switching, setSwitching] = useState(false);

  const normalizedRole = String(user?.role || '').trim().toUpperCase();
  const canSwitchTenant =
    Boolean(user) &&
    (normalizedRole === 'ADMIN' ||
      normalizedRole === 'ROLE_ADMIN' ||
      normalizedRole === 'SUPER_ADMIN' ||
      normalizedRole === 'SUPERADMIN' ||
      normalizedRole.endsWith('_ADMIN') ||
      normalizedRole.includes('ADMIN') ||
      String(user?.username || '').trim().toLowerCase() === 'admin');

  const fetchTenants = async (silent = false) => {
    if (loading) {
      return;
    }

    setLoading(true);
    try {
      const response = await getTenantList({ status: '0' });
      setTenants(Array.isArray(response) ? response : []);
    } catch (error) {
      console.error('获取租户列表失败:', error);
      if (!silent) {
        toast.error('获取租户列表失败');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!canSwitchTenant) {
      return;
    }

    void fetchTenants(true);
  }, [canSwitchTenant]);

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const handleClickOutside = (event: MouseEvent) => {
      if (!dropdownRef.current?.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsOpen(false);
      }
    };

    document.addEventListener('click', handleClickOutside);
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('click', handleClickOutside);
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen]);

  if (!canSwitchTenant || !user) {
    return null;
  }

  const currentTenant = tenants.find((tenant) => tenant.tenantId === user.tenantId);
  const currentTenantLabel = getTenantLabel(currentTenant?.tenantName, user.tenantId);

  const handleSwitchTenant = async (tenantId: number) => {
    if (tenantId === user.tenantId) {
      setIsOpen(false);
      return;
    }

    setSwitching(true);
    try {
      await switchTenant(tenantId);
      setIsOpen(false);
    } catch (error) {
      console.error('租户切换失败:', error);
    } finally {
      setSwitching(false);
    }
  };

  return (
    <div ref={dropdownRef} className="relative">
      <button
        type="button"
        onClick={() => setIsOpen((prev) => !prev)}
        disabled={switching}
        aria-expanded={isOpen}
        aria-haspopup="menu"
        aria-label={`当前租户：${currentTenantLabel}`}
        className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-100 disabled:cursor-wait disabled:opacity-70"
      >
        <Building2 size={15} className="shrink-0 text-gray-400" />
        <span className="hidden max-w-[5.75rem] truncate text-gray-700 sm:inline">
          {currentTenantLabel}
        </span>
        {switching ? (
          <Loader2 size={14} className="animate-spin text-gray-400" />
        ) : (
          <ChevronDown
            size={14}
            className={`text-gray-400 transition-transform duration-200 ${
              isOpen ? 'rotate-180' : ''
            }`}
          />
        )}
      </button>

      <div
        className={`absolute right-0 top-full z-50 mt-1 w-40 origin-top-right overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_18px_36px_rgba(15,23,42,0.12)] ring-1 ring-slate-200/70 transition-all duration-150 ${
          isOpen
            ? 'pointer-events-auto translate-y-0 scale-100 opacity-100'
            : 'pointer-events-none -translate-y-1 scale-95 opacity-0'
        }`}
      >
        {loading ? (
          <div className="flex items-center justify-center gap-2 px-3 py-3 text-sm text-slate-500">
            <Loader2 size={14} className="animate-spin" />
            <span>正在加载</span>
          </div>
        ) : tenants.length === 0 ? (
          <div className="px-3 py-3 text-center text-sm text-slate-500">暂无租户</div>
        ) : (
          <div className="py-1">
            {tenants.map((tenant) => {
              const active = tenant.tenantId === user.tenantId;
              const tenantLabel = getTenantLabel(tenant.tenantName, tenant.tenantId);

              return (
                <button
                  key={tenant.tenantId}
                  type="button"
                  onClick={() => void handleSwitchTenant(tenant.tenantId)}
                  disabled={switching}
                  title={tenantLabel}
                  className={`flex w-full items-center gap-2 px-3 py-2 text-sm text-slate-700 transition-colors hover:bg-slate-50 ${
                    active ? 'bg-cyan-50 text-cyan-600' : ''
                  } ${switching ? 'cursor-not-allowed opacity-70' : ''}`}
                >
                  <Building2
                    size={15}
                    className={`shrink-0 ${active ? 'text-cyan-500' : 'text-slate-400'}`}
                  />
                  <span className="flex-1 truncate text-left">{tenantLabel}</span>
                  {active ? <Check size={14} className="shrink-0 text-cyan-500" /> : null}
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

// cloudflow-frontend-vue/src/components/TenantSwitcher.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { Building2, Check, ChevronDown, Loader2 } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { useToastStore } from '@/stores/toast'
import { getTenantList, type SysTenant, type TenantListResponse } from '@/services/api/tenant'
import { getErrorMessage } from '@/utils/errorMessage'

const auth = useAuthStore()
const toast = useToastStore()
const dropdownRef = ref<HTMLElement | null>(null)
const tenants = ref<SysTenant[]>([])
const isOpen = ref(false)
const loading = ref(false)
const switching = ref(false)

const pickTenantArray = (source?: { records?: SysTenant[]; rows?: SysTenant[]; list?: SysTenant[] }) => {
  if (Array.isArray(source?.records)) return source.records
  if (Array.isArray(source?.rows)) return source.rows
  if (Array.isArray(source?.list)) return source.list
  return []
}

const normalizeTenantListResponse = (response: TenantListResponse): SysTenant[] => {
  if (Array.isArray(response)) return response
  const directList = pickTenantArray(response)
  return directList.length > 0 ? directList : pickTenantArray(response?.data)
}

const normalizedRole = computed(() => String(auth.user?.role || '').trim().toUpperCase())
const canSwitchTenant = computed(() => {
  const username = String(auth.user?.username || '').trim().toLowerCase()
  const role = normalizedRole.value
  return Boolean(auth.user) && (
    role === 'ADMIN' ||
    role === 'ROLE_ADMIN' ||
    role === 'SUPER_ADMIN' ||
    role === 'SUPERADMIN' ||
    role.endsWith('_ADMIN') ||
    role.includes('ADMIN') ||
    username === 'admin'
  )
})

const getTenantName = (tenantName?: string, tenantId?: number) => {
  const normalizedName = String(tenantName || '').trim()
  if (normalizedName) return normalizedName
  return typeof tenantId === 'number' ? `租户 ${tenantId}` : '默认租户'
}

const getTenantIdText = (tenantId?: number) => typeof tenantId === 'number' ? `ID ${tenantId}` : 'ID --'

const currentTenant = computed(() => tenants.value.find((tenant) => tenant.tenantId === auth.user?.tenantId))
const currentTenantName = computed(() => getTenantName(currentTenant.value?.tenantName || auth.user?.tenantName, auth.user?.tenantId))
const currentTenantIdText = computed(() => getTenantIdText(auth.user?.tenantId))

const fetchTenants = async (silent = false) => {
  if (loading.value) return
  loading.value = true
  try {
    const response = await getTenantList({ status: '0' })
    tenants.value = normalizeTenantListResponse(response)
  } catch (error) {
    if (!silent) toast.error(getErrorMessage(error, '获取租户列表失败'))
  } finally {
    loading.value = false
  }
}

const handleSwitchTenant = async (tenantId: number) => {
  if (tenantId === auth.user?.tenantId) {
    isOpen.value = false
    return
  }
  switching.value = true
  try {
    await auth.switchTenant(tenantId)
    isOpen.value = false
  } catch (error) {
    toast.error(getErrorMessage(error, '租户切换失败'))
  } finally {
    switching.value = false
  }
}

const toggleOpen = () => {
  isOpen.value = !isOpen.value
  if (isOpen.value && tenants.value.length === 0) void fetchTenants()
}

const handleClickOutside = (event: MouseEvent) => {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) isOpen.value = false
}

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape') isOpen.value = false
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  window.addEventListener('keydown', handleKeyDown)
  if (canSwitchTenant.value) void fetchTenants(true)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClickOutside)
  window.removeEventListener('keydown', handleKeyDown)
})
</script>

<template>
  <div v-if="canSwitchTenant && auth.user" ref="dropdownRef" class="relative">
    <button
      type="button"
      class="flex items-center gap-2 rounded-lg px-2 py-1.5 text-left text-sm transition-colors hover:bg-gray-100 disabled:cursor-wait disabled:opacity-70 dark:hover:bg-dark-700"
      :disabled="switching"
      :aria-expanded="isOpen"
      aria-haspopup="menu"
      :aria-label="`当前租户：${currentTenantName}`"
      @click.stop="toggleOpen"
    >
      <div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 dark:border-dark-700 dark:bg-dark-800 dark:text-dark-300">
        <Building2 :size="15" />
      </div>
      <div class="hidden min-w-0 flex-1 sm:block">
        <div class="truncate text-sm font-semibold text-slate-700 dark:text-slate-100">{{ currentTenantName }}</div>
        <div class="truncate text-[11px] text-slate-500 dark:text-slate-400">{{ currentTenantIdText }}</div>
      </div>
      <Loader2 v-if="switching" :size="14" class="shrink-0 animate-spin text-slate-400" />
      <ChevronDown v-else :size="14" class="shrink-0 text-slate-400 transition-transform duration-200" :class="isOpen ? 'rotate-180' : ''" />
    </button>

    <div class="absolute right-0 top-full z-50 mt-2 w-56 origin-top-right overflow-hidden rounded-xl border border-gray-200 bg-white shadow-lg transition duration-150 dark:border-dark-700 dark:bg-dark-800" :class="isOpen ? 'pointer-events-auto translate-y-0 scale-100 opacity-100' : 'pointer-events-none -translate-y-1 scale-95 opacity-0'">
      <div v-if="loading" class="flex items-center justify-center gap-2 px-4 py-4 text-sm text-slate-500 dark:text-slate-400">
        <Loader2 :size="14" class="animate-spin" />
        <span>正在加载</span>
      </div>
      <div v-else-if="tenants.length === 0" class="px-4 py-4 text-center text-sm text-slate-500 dark:text-slate-400">暂无租户</div>
      <div v-else class="py-1.5">
        <button
          v-for="tenant in tenants"
          :key="tenant.tenantId"
          type="button"
          class="flex w-full items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-gray-50 dark:hover:bg-dark-700/50"
          :class="[tenant.tenantId === auth.user.tenantId ? 'bg-primary-50 dark:bg-primary-900/20' : '', switching ? 'cursor-not-allowed opacity-70' : '']"
          :disabled="switching"
          :title="`${getTenantName(tenant.tenantName, tenant.tenantId)} ${getTenantIdText(tenant.tenantId)}`"
          @click="handleSwitchTenant(tenant.tenantId)"
        >
          <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-gray-200 bg-white text-gray-400 dark:border-dark-700 dark:bg-dark-900" :class="tenant.tenantId === auth.user.tenantId ? 'border-primary-200 bg-primary-100 text-primary-600 dark:border-primary-800 dark:bg-primary-900/30 dark:text-primary-300' : ''">
            <Building2 :size="15" />
          </div>
          <div class="min-w-0 flex-1">
            <div class="truncate text-sm font-medium" :class="tenant.tenantId === auth.user.tenantId ? 'text-cyan-700 dark:text-cyan-200' : 'text-slate-700 dark:text-slate-200'">
              {{ getTenantName(tenant.tenantName, tenant.tenantId) }}
            </div>
            <div class="mt-0.5 truncate text-[11px]" :class="tenant.tenantId === auth.user.tenantId ? 'text-cyan-600/80 dark:text-cyan-300/80' : 'text-slate-500 dark:text-slate-400'">
              {{ getTenantIdText(tenant.tenantId) }}
            </div>
          </div>
          <Check v-if="tenant.tenantId === auth.user.tenantId" :size="14" class="shrink-0 text-cyan-500 dark:text-cyan-300" />
        </button>
      </div>
    </div>
  </div>
</template>
