// cloudflow-frontend-vue/src/components/common/AnnouncementBell.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import Icon from '@/components/icons/Icon.vue'
import { useAnnouncementStore } from '@/stores/announcement'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errorMessage'
import type { Announcement } from '@/types'

const announcementStore = useAnnouncementStore()
const toast = useToastStore()
const router = useRouter()
const isOpen = ref(false)
const dropdownRef = ref<HTMLElement | null>(null)

const unreadCount = computed(() => announcementStore.unreadCount)
const announcements = computed(() => announcementStore.announcements.slice(0, 6))

function formatTime(value?: string) {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
}

async function openDetail(item: Announcement) {
  isOpen.value = false
  if (!item.isRead) {
    try {
      await announcementStore.markAsRead(item.announcementId)
    } catch (error) {
      toast.error(getErrorMessage(error, '标记公告已读失败'))
    }
  }
  router.push('/announcement')
}

async function markAllAsRead() {
  try {
    await announcementStore.markAllAsRead()
    toast.success('所有公告已标记为已读')
  } catch (error) {
    toast.error(getErrorMessage(error, '标记公告已读失败'))
  }
}

function handleClickOutside(event: MouseEvent) {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    isOpen.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  void announcementStore.fetchAnnouncements()
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<template>
  <div ref="dropdownRef" class="relative">
    <button
      type="button"
      class="relative rounded-lg p-2 text-gray-600 transition-colors hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-dark-700"
      aria-label="公告"
      @click.stop="isOpen = !isOpen"
    >
      <Icon name="bell" size="md" />
      <span v-if="unreadCount > 0" class="absolute right-1 top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] font-semibold leading-none text-white">
        {{ unreadCount > 99 ? '99+' : unreadCount }}
      </span>
    </button>

    <transition name="dropdown">
      <div v-if="isOpen" class="absolute right-0 z-50 mt-2 w-[22rem] overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-lg dark:border-dark-700 dark:bg-dark-800">
        <div class="flex items-center justify-between border-b border-gray-100 px-4 py-3 dark:border-dark-700">
          <div>
            <p class="text-sm font-semibold text-gray-900 dark:text-white">公告</p>
            <p class="mt-0.5 text-xs text-gray-500 dark:text-dark-400">未读 {{ unreadCount }} 条</p>
          </div>
          <button v-if="unreadCount > 0" type="button" class="btn btn-ghost btn-sm" @click="markAllAsRead">全部已读</button>
        </div>

        <div class="max-h-[24rem] overflow-y-auto">
          <div v-if="announcementStore.loading" class="empty-state py-10">
            <Icon name="loader" size="lg" class="empty-state-icon animate-spin" />
            <p class="empty-state-title text-sm">正在加载公告</p>
          </div>
          <template v-else-if="announcements.length > 0">
            <button
              v-for="item in announcements"
              :key="item.announcementId"
              type="button"
              class="flex w-full items-start gap-3 border-b border-gray-100 px-4 py-3 text-left transition-colors last:border-b-0 hover:bg-gray-50 dark:border-dark-700 dark:hover:bg-dark-700/50"
              @click="openDetail(item)"
            >
              <span class="mt-1 h-2 w-2 shrink-0 rounded-full" :class="item.isRead ? 'bg-gray-300 dark:bg-dark-600' : 'bg-primary-500'" />
              <span class="min-w-0 flex-1">
                <span class="block truncate text-sm font-medium text-gray-900 dark:text-white">{{ item.title }}</span>
                <span class="mt-1 block truncate text-xs text-gray-500 dark:text-dark-400">{{ formatTime(item.publishTime || item.createTime) }}</span>
              </span>
            </button>
          </template>
          <div v-else class="empty-state py-10">
            <Icon name="inbox" size="lg" class="empty-state-icon" />
            <p class="empty-state-title text-sm">暂无公告</p>
            <p class="empty-state-description text-xs">新公告发布后会显示在这里</p>
          </div>
        </div>

        <button type="button" class="flex w-full items-center justify-center gap-2 border-t border-gray-100 px-4 py-3 text-sm font-medium text-primary-600 transition-colors hover:bg-primary-50 dark:border-dark-700 dark:hover:bg-primary-900/20" @click="isOpen = false; router.push('/announcement')">
          查看公告中心
          <Icon name="chevronRight" size="sm" />
        </button>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: scale(0.95) translateY(-4px);
}
</style>

// cloudflow-frontend/src/components/common/AnnouncementBell.tsx
import React, { useEffect, useState } from 'react';
import { Bell, Check, ChevronRight, Inbox, Info, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { BaseDialog } from '@/components/common/BaseDialog';
import { getErrorMessage } from '@/utils/errorMessage';
import { AnnouncementDetailModal } from '@/components/common/AnnouncementDetailModal';
import { useAnnouncementStore, useAnnouncementUnreadCount } from '@/stores/announcementStore';
import type { Announcement } from '@/types';
import { formatAnnouncementRelativeTime } from '@/utils/announcementFormat';
import './announcement-overlays.css';

export const AnnouncementBell: React.FC = () => {
  const announcements = useAnnouncementStore((state) => state.announcements);
  const loading = useAnnouncementStore((state) => state.loading);
  const fetchAnnouncements = useAnnouncementStore((state) => state.fetchAnnouncements);
  const markAsRead = useAnnouncementStore((state) => state.markAsRead);
  const markAllAsRead = useAnnouncementStore((state) => state.markAllAsRead);
  const unreadCount = useAnnouncementUnreadCount();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedAnnouncement, setSelectedAnnouncement] = useState<Announcement | null>(null);

  useEffect(() => {
    if (!isModalOpen) {
      return;
    }

    void fetchAnnouncements(true);
  }, [fetchAnnouncements, isModalOpen]);

  useEffect(() => {
    if (!isModalOpen) {
      return;
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !selectedAnnouncement) {
        setIsModalOpen(false);
      }
    };

    window.addEventListener('keydown', handleEscape);

    return () => {
      window.removeEventListener('keydown', handleEscape);
    };
  }, [isModalOpen, selectedAnnouncement]);

  function openModal() {
    setIsModalOpen(true);
  }

  function closeModal() {
    setIsModalOpen(false);
  }

  async function openDetail(announcement: Announcement) {
    const nextAnnouncement = announcement.isRead ? announcement : { ...announcement, isRead: true };
    setSelectedAnnouncement(nextAnnouncement);

    if (!announcement.isRead) {
      await markAsRead(announcement.announcementId);
    }
  }

  function closeDetail() {
    setSelectedAnnouncement(null);
  }

  async function markAsReadAndClose(announcementId: number) {
    await markAsRead(announcementId);
    closeDetail();
  }

  async function handleMarkAllAsRead() {
    try {
      await markAllAsRead();
      toast.success('所有公告已标记为已读');
      setSelectedAnnouncement((previous) => (previous ? { ...previous, isRead: true } : previous));
    } catch (error) {
      toast.error(getErrorMessage(error, '标记公告已读失败'));
    }
  }

  return (
    <div>
      <button
        type="button"
        onClick={openModal}
        className={`relative flex h-9 w-9 items-center justify-center rounded-md text-cf-muted transition-colors hover:bg-[var(--cf-surface-muted)] dark:hover:bg-slate-800 ${
 unreadCount > 0 ? 'text-cyan-600 dark:text-cyan-400' : ''
 }`}
        aria-label="公告"
      >
        <Bell size={18} />
        {unreadCount > 0 ? (
          <span className="absolute right-1 top-1 h-2 w-2 rounded-sm bg-red-500" />
        ) : null}
      </button>

      <BaseDialog
        open={isModalOpen}
        title="公告"
        description={unreadCount > 0 ? `${unreadCount} 条未读` : undefined}
        onClose={closeModal}
        closeOnEscape={false}
        maxWidthClassName="w-full max-w-[620px]"
        bodyClassName="p-0 !overflow-hidden"
        headerAside={(
          <>
            <Bell size={16} className="text-cyan-600 dark:text-cyan-300" />
            {unreadCount > 0 ? (
              <button
                type="button"
                onClick={() => void handleMarkAllAsRead()}
                disabled={loading}
                className="rounded-md bg-cyan-600 px-4 py-2 text-xs font-medium text-white transition-colors hover:bg-cyan-700 disabled:opacity-50 dark:bg-cyan-500 dark:hover:bg-cyan-600"
              >
                全部已读
              </button>
            ) : null}
          </>
        )}
        zIndex={100}
      >
              <div className="cf-announcement-scroll max-h-[65vh] overflow-y-auto">
                {loading ? (
                  <div className="flex items-center justify-center py-10">
                    <Loader2 className="h-8 w-8 animate-spin text-cyan-600 dark:text-cyan-300" />
                  </div>
                ) : announcements.length > 0 ? (
                  <div>
                    {announcements.map((item) => (
                      <div
                        key={item.announcementId}
                        className={`group relative flex min-h-[72px] items-center gap-4 border-b border-slate-200 px-6 py-4 transition-colors hover:bg-[var(--cf-surface-muted)] dark:border-slate-800 dark:hover:bg-slate-900/70 ${
 !item.isRead ? 'bg-cyan-50/30 dark:bg-cyan-950/10' : ''
 }`}
                        onClick={() => void openDetail(item)}
                      >
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center">
                          {!item.isRead ? (
                            <div className="relative flex h-10 w-10 items-center justify-center rounded-md bg-cyan-600 text-white">
                              <Info className="h-5 w-5" strokeWidth={2.5} />
                            </div>
                          ) : (
                            <div className="flex h-10 w-10 items-center justify-center rounded-md bg-[var(--cf-surface-muted)] text-cf-faint dark:bg-slate-900">
                              <Check className="h-5 w-5" />
                            </div>
                          )}
                        </div>

                        <div className="flex min-w-0 flex-1 items-center justify-between gap-4">
                          <div className="min-w-0 flex-1">
                            <h3 className="truncate text-sm font-medium text-cf-title">
                              {item.title}
                            </h3>
                            <div className="mt-1 flex items-center gap-2">
                              <time className="text-xs text-cf-subtle">
                                {formatAnnouncementRelativeTime(item.publishTime || item.createTime)}
                              </time>
                              {!item.isRead ? (
                                <span className="inline-flex items-center gap-1 rounded-md bg-cyan-100 px-1.5 py-0.5 text-xs font-medium text-cyan-700 dark:bg-cyan-950/30 dark:text-cyan-300">
                                  <span className="h-1.5 w-1.5 rounded-sm bg-cyan-600" />
                                  未读
                                </span>
                              ) : null}
                            </div>
                          </div>

                          <div className="flex-shrink-0">
                            <ChevronRight className="h-5 w-5 text-cf-faint transition-transform group-hover:translate-x-1" />
                          </div>
                        </div>

                        {!item.isRead ? (
                          <div className="absolute left-0 top-0 h-full w-1 bg-cyan-600" />
                        ) : null}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-10">
                    <div className="relative mb-4">
                      <div className="flex h-20 w-20 items-center justify-center rounded-md border border-slate-200 bg-[var(--cf-surface-strong)] dark:border-slate-800 dark:bg-slate-950">
                        <Inbox size={28} className="text-cf-faint" />
                      </div>
                      <div className="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-md bg-cyan-600 text-white">
                        <Check className="h-3.5 w-3.5" />
                      </div>
                    </div>
                    <p className="text-sm font-medium text-cf-title">暂无公告</p>
                    <p className="mt-1 text-xs text-cf-subtle">暂时没有任何系统公告</p>
                  </div>
                )}
              </div>
      </BaseDialog>

      <AnnouncementDetailModal
        announcement={selectedAnnouncement}
        onClose={closeDetail}
        onMarkAsRead={markAsReadAndClose}
        zIndexClassName="z-[110]"
      />
    </div>
  );
};
