// cloudflow-frontend-vue/src/components/common/BaseDialog.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import Icon from '@/components/icons/Icon.vue'

type DialogWidth = 'narrow' | 'normal' | 'wide' | 'extra-wide' | 'full'

const props = withDefaults(defineProps<{
  show: boolean
  title: string
  width?: DialogWidth
  closeOnEscape?: boolean
  closeOnClickOutside?: boolean
  zIndex?: number
}>(), {
  width: 'normal',
  closeOnEscape: true,
  closeOnClickOutside: false,
  zIndex: 50
})

const emit = defineEmits<{ close: [] }>()

let dialogIdCounter = 0
const dialogId = `cf-dialog-title-${++dialogIdCounter}`
const dialogRef = ref<HTMLElement | null>(null)
let previousActiveElement: HTMLElement | null = null

const zIndexStyle = computed(() => (props.zIndex !== 50 ? { zIndex: props.zIndex } : undefined))
const widthClasses = computed(() => {
  const widths: Record<DialogWidth, string> = {
    narrow: 'max-w-md',
    normal: 'max-w-lg',
    wide: 'w-full sm:max-w-2xl md:max-w-3xl lg:max-w-4xl',
    'extra-wide': 'w-full sm:max-w-3xl md:max-w-4xl lg:max-w-5xl xl:max-w-6xl',
    full: 'w-full sm:max-w-4xl md:max-w-5xl lg:max-w-6xl xl:max-w-7xl'
  }
  return widths[props.width]
})

const handleClose = () => {
  if (props.closeOnClickOutside) emit('close')
}

const handleEscape = (event: KeyboardEvent) => {
  if (props.show && props.closeOnEscape && event.key === 'Escape') emit('close')
}

watch(
  () => props.show,
  async (isOpen) => {
    if (isOpen) {
      previousActiveElement = document.activeElement as HTMLElement
      document.body.classList.add('modal-open')
      await nextTick()
      dialogRef.value?.querySelector<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')?.focus()
    } else {
      document.body.classList.remove('modal-open')
      previousActiveElement?.focus?.()
      previousActiveElement = null
    }
  },
  { immediate: true }
)

onMounted(() => document.addEventListener('keydown', handleEscape))
onUnmounted(() => {
  document.removeEventListener('keydown', handleEscape)
  document.body.classList.remove('modal-open')
})
</script>

<template>
  <Teleport to="body">
    <Transition name="modal">
      <div
        v-if="show"
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/48 p-4 backdrop-blur-[2px]"
        :style="zIndexStyle"
        :aria-labelledby="dialogId"
        role="dialog"
        aria-modal="true"
        @click.self="handleClose"
      >
        <div ref="dialogRef" class="max-h-[90vh] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_28px_70px_-30px_rgba(15,23,42,0.34)] dark:border-slate-700 dark:bg-slate-950" :class="widthClasses" @click.stop>
          <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800">
            <h3 :id="dialogId" class="text-base font-semibold text-slate-900 dark:text-slate-100">{{ title }}</h3>
            <button type="button" class="-mr-2 rounded-xl p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800 dark:hover:text-slate-200" aria-label="关闭弹窗" @click="emit('close')">
              <Icon name="x" size="md" />
            </button>
          </div>
          <div class="max-h-[calc(90vh-8rem)] overflow-y-auto p-5">
            <slot />
          </div>
          <div v-if="$slots.footer" class="border-t border-slate-100 px-5 py-4 dark:border-slate-800">
            <slot name="footer" />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style>
body.modal-open {
  overflow: hidden;
}

.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.18s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
</style>

// cloudflow-frontend/src/components/common/BaseDialog.tsx
import React, { useEffect, useId, useRef } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';
import { cn } from '@/utils/cn';
import { lockBodyScroll } from '@/utils/bodyScrollLock';

export type BaseDialogWidth = 'narrow' | 'normal' | 'wide' | 'extra-wide' | 'full';

interface BaseDialogProps {
  open: boolean;
  title: React.ReactNode;
  description?: React.ReactNode;
  onClose: () => void;
  children: React.ReactNode;
  footer?: React.ReactNode;
  width?: BaseDialogWidth;
  maxWidthClassName?: string;
  headerAside?: React.ReactNode;
  bodyClassName?: string;
  footerClassName?: string;
  panelClassName?: string;
  closeOnClickOutside?: boolean;
  closeOnEscape?: boolean;
  zIndex?: number;
}

export const BaseDialog: React.FC<BaseDialogProps> = ({
  open,
  title,
  description,
  onClose,
  children,
  footer,
  width = 'normal',
  maxWidthClassName,
  headerAside,
  bodyClassName,
  footerClassName,
  panelClassName,
  closeOnClickOutside = false,
  closeOnEscape = true,
  zIndex = 50,
}) => {
  const titleId = useId();
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const previousActiveElementRef = useRef<HTMLElement | null>(null);
  const widthClassMap: Record<BaseDialogWidth, string> = {
    narrow: 'max-w-md',
    normal: 'max-w-lg',
    wide: 'w-full sm:max-w-2xl md:max-w-3xl lg:max-w-4xl',
    'extra-wide': 'w-full sm:max-w-3xl md:max-w-4xl lg:max-w-5xl xl:max-w-6xl',
    full: 'w-full sm:max-w-4xl md:max-w-5xl lg:max-w-6xl xl:max-w-7xl',
  };
  const resolvedMaxWidthClassName = maxWidthClassName || widthClassMap[width];
  const hasCustomPanelMaxHeight = Boolean(panelClassName && /(^|\s)!?max-h-/.test(panelClassName));
  const hasCustomBodyOverflow = Boolean(bodyClassName && /(^|\s)!?overflow(?:-[xy])?-/.test(bodyClassName));

  useEffect(() => {
    if (!open) {
      return;
    }

    previousActiveElementRef.current = document.activeElement as HTMLElement;

    const handleEscape = (event: KeyboardEvent) => {
      if (closeOnEscape && event.key === 'Escape') {
        onClose();
      }
    };

    const unlockBodyScroll = lockBodyScroll();
    window.addEventListener('keydown', handleEscape);
    window.requestAnimationFrame(() => {
      const firstFocusable = dialogRef.current?.querySelector<HTMLElement>(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
      );
      firstFocusable?.focus();
    });

    return () => {
      unlockBodyScroll();
      window.removeEventListener('keydown', handleEscape);
      previousActiveElementRef.current?.focus?.();
      previousActiveElementRef.current = null;
    };
  }, [closeOnEscape, onClose, open]);

  if (!open) {
    return null;
  }

  return createPortal(
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/48 p-2 backdrop-blur-sm sm:p-4"
      style={zIndex === 50 ? undefined : { zIndex }}
      onClick={() => {
        if (closeOnClickOutside) {
          onClose();
        }
      }}
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
    >
      <div
        ref={dialogRef}
        className={cn(
          'w-full overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_22px_44px_rgba(15,23,42,0.14)] ring-1 ring-slate-200/80 dark:border-slate-800 dark:bg-slate-950 dark:ring-slate-800/80 dark:shadow-[0_28px_56px_rgba(2,6,23,0.56)]',
          'flex flex-col',
          !hasCustomPanelMaxHeight && 'max-h-[95vh] sm:max-h-[90vh]',
          resolvedMaxWidthClassName,
          panelClassName,
        )}
        onClick={(event) => event.stopPropagation()}
      >
        <div className="flex flex-shrink-0 items-start justify-between gap-4 border-b border-slate-100 px-4 py-3 sm:px-6 sm:py-4 dark:border-slate-800">
          <div className="min-w-0">
            <h3 id={titleId} className="text-lg font-semibold text-slate-900 dark:text-slate-100">
              {title}
            </h3>
            {description ? (
              <div className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">
                {description}
              </div>
            ) : null}
          </div>
          <div className="ml-4 flex items-center gap-2">
            {headerAside}
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 dark:text-slate-500 dark:hover:bg-slate-800 dark:hover:text-slate-200"
              aria-label="关闭弹窗"
            >
              <X size={18} />
            </button>
          </div>
        </div>
        <div
          className={cn(
            'min-h-0 flex-1 px-4 py-3 sm:px-6 sm:py-4',
            !hasCustomBodyOverflow && 'overflow-y-auto',
            bodyClassName,
          )}
        >
          {children}
        </div>
        {footer ? (
          <div
            className={cn(
              'flex flex-shrink-0 items-center justify-end gap-3 border-t border-slate-100 bg-slate-50/70 px-4 py-3 sm:px-6 sm:py-4 dark:border-slate-800 dark:bg-slate-900/70',
              footerClassName,
            )}
          >
            {footer}
          </div>
        ) : null}
      </div>
    </div>,
    document.body,
  );
};
